In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\nazom\OneDrive\Documents\Python Scripts\Pandas Folder\WorldContinents.csv', encoding = 'ISO-8859-1')
pd.set_option('display.max.rows',1350)
pd.set_option('display.max.columns',15)

In [3]:
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [4]:
df.loc[0]

continent              Asia
sub_region    Southern Asia
country         Afghanistan
code_3                  AFG
Unnamed: 4       6,900,000
Name: 0, dtype: object

In [5]:
df.iloc[0]

continent              Asia
sub_region    Southern Asia
country         Afghanistan
code_3                  AFG
Unnamed: 4       6,900,000
Name: 0, dtype: object

In [6]:
#loc is a a name based index while iloc is intger based index

In [7]:
df.set_index(['country'], inplace = True)

In [8]:
df

,continent,sub_region,code_3,Unnamed: 4
country,,,,
Afghanistan,Asia,Southern Asia,AFG,"6,900,000"
Åland Islands,Europe,Northern Europe,ALA,"5,500,000"
Albania,Europe,Southern Europe,ALB,"3,300,000"
Algeria,Africa,Northern Africa,DZA,"9,500,000"
American Samoa,Oceania,Polynesia,ASM,"55,000"
Andorra,Europe,Southern Europe,AND,"77,000"
Angola,Africa,Middle Africa,AGO,"54,000,000"
Anguilla,Americas,Caribbean,AIA,"2,100,000"
Antigua and Barbuda,Americas,Caribbean,ATG,"98,000"
Argentina,Americas,South America,ARG,"45,000,000"
Armenia,Asia,Western Asia,ARM,"45,700,000"
Aruba,Americas,Caribbean,ABW,"11,600,000"
Australia,Oceania,Australia and New Zealand,AUS,"36,000,000"
Austria,Europe,Western Europe,AUT,"9,000,000"
Azerbaijan,Asia,Western Asia,AZE,"10,000,000"
Bahamas,Americas,Caribbean,BHS,"7,500,000"
Bahrain,Asia,Western Asia,BHR,"1,900,000"
Bangladesh,Asia,Southern Asia,BGD,"2,500,000"
Barbados,Americas,Caribbean,BRB,"44,000,000"
Belarus,Europe,Eastern Europe,BLR,"9,400,000"
Belgium,Europe,Western Europe,BEL,"12,000,000"
Belize,Americas,Central America,BLZ,"9,000,000"
Benin,Africa,Western Africa,BEN,"17,400,000"
Bermuda,Americas,Northern America,BMU,"64,000"
Bhutan,Asia,Southern Asia,BTN,"771,000"
Bolivia (Plurinational State of),Americas,South America,BOL,"12,900,000"
"Bonaire, Sint Eustatius and Saba",Americas,Caribbean,BES,"4,300,000"
Bosnia and Herzegovina,Europe,Southern Europe,BIH,"5,000,000"
Botswana,Africa,Southern Africa,BWA,"29,000,000"
Brazil,Americas,South America,BRA,"32,700,000"
Brunei Darussalam,Asia,South-Eastern Asia,BRN,"9,400,000"
Bulgaria,Europe,Eastern Europe,BGR,"6,900,000"
Burkina Faso,Africa,Western Africa,BFA,"31,000,000"
Burundi,Africa,Eastern Africa,BDI,"128,000,000"
Cabo Verde,Africa,Western Africa,CPV,"556,000"
Cambodia,Asia,South-Eastern Asia,KHM,"2,200,000"
Cameroon,Africa,Middle Africa,CMR,"38,000,000"
Canada,Americas,Northern America,CAN,"60,000,000"
Cayman Islands,Americas,Caribbean,CYM,"66,000"
Central African Republic,Africa,Middle Africa,CAF,"84,000,000"
Chad,Africa,Middle Africa,TCD,"2,100,000"
Chile,Americas,South America,CHL,"25,000,000"
China,Asia,Eastern Asia,CHN,"1,412,000,000"
Colombia,Americas,South America,COL,"51,000,000"
Comoros,Africa,Eastern Africa,COM,"870,000"
Congo,Africa,Middle Africa,COG,"5,500,000"
Congo (Democratic Republic of the),Africa,Middle Africa,COD,"89,000,000"
Cook Islands,Oceania,Polynesia,COK,"206,000,000"
Costa Rica,Americas,Central America,CRI,"5,100,000"
Côte d'Ivoire,Africa,Western Africa,CIV,"38,000,000"
Croatia,Europe,Southern Europe,HRV,"7,900,000"
Cuba,Americas,Caribbean,CUB,"110,000,000"
Curaçao,Americas,Caribbean,CUW,"2,600,000"
Cyprus,Asia,Western Asia,CYP,"1,200,000"
Czech Republic,Europe,Eastern Europe,CZE,"102,000,000"
Denmark,Europe,Northern Europe,DNK,"5,800,000"
Djibouti,Africa,Eastern Africa,DJI,"988,000"
Dominica,Americas,Caribbean,DMA,"72,000"
Dominican Republic,Americas,Caribbean,DOM,"11,200,000"
Ecuador,Americas,South America,ECU,"2,900,000"
Egypt,Africa,Northern Africa,EGY,"11,300,000"
El Salvador,Americas,Central America,SLV,"6,500,000"
Equatorial Guinea,Africa,Middle Africa,GNQ,"1,700,000"
Eritrea,Africa,Eastern Africa,ERI,"5,100,000"
Estonia,Europe,Northern Europe,EST,"1,300,000"
Ethiopia,Africa,Eastern Africa,ETH,"16,700,000"
Falkland Islands (Malvinas),Americas,South America,FLK,"5,500,000"
Faroe Islands,Europe,Northern Europe,FRO,"49,000"
Fiji,Oceania,Melanesia,FJI,"896,000"
Finland,Europe,Northern Europe,FIN,"5,500,000"
France,Europe,Western Europe,FRA,"67,000,000"
French Guiana,Americas,South America,GUF,"45,000,000"
French Polynesia,Oceania,Polynesia,PYF,"40,000,000"
Gabon,Africa,Middle Africa,GAB,"28,000,000"
Gambia,Africa,Western Africa,GMB,"3,000,000"
Georgia,Asia,Western Asia,GEO,"5,400,000"
Germany,Europe,Western Europe,DEU,"83,200,000"
Ghana,Africa,Western Africa,GHA,"51,000,000"
Gibraltar,Europe,Southern Europe,GIB,"6,500,000"
Greece,Europe,Southern Europe,GRC,"10,800,000"
Greenland,Americas,Northern America,GRL,"56,000"
Grenada,Americas,Caribbean,GRD,"16,700,000"
Guadeloupe,Americas,Caribbean,GLP,"9,000,000"
Guam,Oceania,Micronesia,GUM,"2,800,000"
Guatemala,Americas,Central America,GTM,"21,000,000"
Guernsey,Europe,Northern Europe,GGY,"63,000"
Guinea,Africa,Western Africa,GIN,"18,700,000"
Guinea-Bissau,Africa,Western Africa,GNB,"10,000,000"
Guyana,Americas,South America,GUY,"787,000"
Haiti,Americas,Caribbean,HTI,"114,000,000"
Holy See,Europe,Southern Europe,VAT,800
Honduras,Americas,Central America,HND,"10,000,000"
Hong Kong,Asia,Eastern Asia,HKG,"7,500,000"
Hungary,Europe,Eastern Europe,HUN,"9,600,000"
Iceland,Europe,Northern Europe,ISL,"6,900,000"
India,Asia,Southern Asia,IND,"1,400,000,000"
Indonesia,Asia,South-Eastern Asia,IDN,"4,600,000"
Iran (Islamic Republic of),Asia,Southern Asia,IRN,"84,000,000"
Iraq,Asia,Western Asia,IRQ,"89,000,000"
Ireland,Europe,Northern Europe,IRL,"5,000,000"
Isle of Man,Europe,Northern Europe,IMN,"85,000"
Israel,Asia,Western Asia,ISR,"9,300,000"
Italy,Europe,Southern Europe,ITA,"60,000,000"
Jamaica,Americas,Caribbean,JAM,"3,700,000"
Japan,Asia,Eastern Asia,JPN,"18,000,000"
Jersey,Europe,Northern Europe,JEY,"11,800,000"
Jordan,Asia,Western Asia,JOR,"10,300,000"
Kazakhstan,Asia,Central Asia,KAZ,"22,000,000"
Kenya,Africa,Eastern Africa,KEN,"53,800,000"
Kiribati,Oceania,Micronesia,KIR,"17,600,000"
Korea (Democratic People's Republic of),Asia,Eastern Asia,PRK,"38,000,000"
Korea (Republic of),Asia,Eastern Asia,KOR,"51,600,000"
Kuwait,Asia,Western Asia,KWT,"8,300,000"
Kyrgyzstan,Asia,Central Asia,KGZ,"6,600,000"
Lao People's Democratic Republic,Asia,South-Eastern Asia,LAO,"7,300,000"
Latvia,Europe,Northern Europe,LVA,"10,000,000"
Lebanon,Asia,Western Asia,LBN,"6,800,000"
Lesotho,Africa,Southern Africa,LSO,"27,700,000"
Liberia,Africa,Western Africa,LBR,"5,000,000"
Libya,Africa,Northern Africa,LBY,"6,900,000"
Liechtenstein,Europe,Western Europe,LIE,"68,000,000"
Lithuania,Europe,Northern Europe,LTU,"3,500,000"
Luxembourg,Europe,Western Europe,LUX,"633,000"
Macao,Asia,Eastern Asia,MAC,"650,000"
Macedonia (the former Yugoslav Republic of),Europe,Southern Europe,MKD,"26,000,000"
Madagascar,Africa,Eastern Africa,MDG,"4,300,000"
Malawi,Africa,Eastern Africa,MWI,"25,800,000"
Malaysia,Asia,South-Eastern Asia,MYS,"53,800,000"
Maldives,Asia,Southern Asia,MDV,"540,000"
Mali,Africa,Western Africa,MLI,"30,000,000"
Malta,Europe,Southern Europe,MLT,"97,000,000"
Marshall Islands,Oceania,Micronesia,MHL,"59,000"
Martinique,Americas,Caribbean,MTQ,"6,900,000"
Mauritania,Africa,Western Africa,MRT,"83,200,000"
Mauritius,Africa,Eastern Africa,MUS,"1,300,000"
Mayotte,Africa,Eastern Africa,MYT,"4,800,000"
Mexico,Americas,Central America,MEX,"18,400,000"
Micronesia (Federated States of),Oceania,Micronesia,FSM,"164,000,000"
Moldova (Republic of),Europe,Eastern Europe,MDA,"3,300,000"
Monaco,Europe,Western Europe,MCO,"7,100,000"
Mongolia,Asia,Eastern Asia,MNG,"5,000,000"
Montenegro,Europe,Southern Europe,MNE,"622,000"
Montserrat,Americas,Caribbean,MSR,"5,000"
Morocco,Africa,Northern Africa,MAR,"6,800,000"
Mozambique,Africa,Eastern Africa,MOZ,"51,600,000"
Myanmar,Asia,South-Eastern Asia,MMR,"54,000,000"
Namibia,Africa,Southern Africa,NAM,"3,200,000"
Nauru,Oceania,Micronesia,NRU,"144,000,000"
Nepal,Asia,Southern Asia,NPL,"44,000,000"
Netherlands,Europe,Western Europe,NLD,"2,800,000"
New Caledonia,Oceania,Melanesia,NCL,"44,000,000"
New Zealand,Oceania,Australia and New Zealand,NZL,"84,000,000"
Nicaragua,Americas,Central America,NIC,"6,600,000"
Niger,Africa,Western Africa,NER,"35,000,000"
Nigeria,Africa,Western Africa,NGA,"31,000,000"
Niue,Oceania,Polynesia,NIU,"2,400,000"
Norfolk Island,Oceania,Australia and New Zealand,NFK,"20,300,000"
Northern Mariana Islands,Oceania,Micronesia,MNP,"58,000"
Norway,Europe,Northern Europe,NOR,"5,400,000"
Oman,Asia,Western Asia,OMN,"5,000,000"
Pakistan,Asia,Southern Asia,PAK,"331,000,000"
Palau,Oceania,Micronesia,PLW,"220,000,000"
"Palestine, State of",Asia,Western Asia,PSE,"5,100,000"
Panama,Americas,Central America,PAN,"8,700,000"
Papua New Guinea,Oceania,Melanesia,PNG,"9,000,000"
Paraguay,Americas,South America,PRY,"7,100,000"
Peru,Americas,South America,PER,"59,000,000"
Philippines,Asia,South-Eastern Asia,PHL,"13,100,000"
Pitcairn,Oceania,Polynesia,PCN,"50,000,000"
Poland,Europe,Eastern Europe,POL,"67,000,000"
Portugal,Europe,Southern Europe,PRT,"10,400,000"
Puerto Rico,Americas,Caribbean,PRI,"47,000,000"
Qatar,Asia,Western Asia,QAT,"3,500,000"
Réunion,Africa,Eastern Africa,REU,"859,000"
Romania,Europe,Eastern Europe,ROU,"24,000,000"
Russian Federation,Europe,Eastern Europe,RUS,"19,000,000"
Rwanda,Africa,Eastern Africa,RWA,"17,500,000"
Saint Barthélemy,Americas,Caribbean,BLM,"9,900"
"Saint Helena, Ascension and Tristan da Cunha",Africa,Western Africa,SHN,"6,000"
Saint Kitts and Nevis,Americas,Caribbean,KNA,"53,000"
Saint Lucia,Americas,Caribbean,LCA,"23,800,000"
Saint Martin (French part),Americas,Caribbean,MAF,"7,300,000"
Saint Pierre and Miquelon,Americas,Northern America,SPM,"5,700"
Saint Vincent and the Grenadines,Americas,Caribbean,VCT,"16,400,000"
Samoa,Oceania,Polynesia,WSM,"26,000,000"
San Marino,Europe,Southern Europe,SMR,"6,600,000"
Sao Tome and Principe,Africa,Middle Africa,STP,"33,000,000"
Saudi Arabia,Asia,Western Asia,SAU,"6,600,000"
Senegal,Africa,Western Africa,SEN,"2,300,000"
Serbia,Europe,Southern Europe,SRB,"6,900,000"
Seychelles,Africa,Eastern Africa,SYC,"98,000"
Sierra Leone,Africa,Western Africa,SLE,"7,900,000"
Singapore,Asia,South-Eastern Asia,SGP,"5,900,000"
Sint Maarten (Dutch part),Americas,Caribbean,SXM,"9,300,000"
Slovakia,Europe,Eastern Europe,SVK,"5,500,000"
Slovenia,Europe,Southern Europe,SVN,"276,000,000"
Solomon Islands,Oceania,Melanesia,SLB,"686,000"
Somalia,Africa,Eastern Africa,SOM,"19,100,000"
South Africa,Africa,Southern Africa,ZAF,"59,000,000"
South Sudan,Africa,Eastern Africa,SSD,"11,900,000"
Spain,Europe,Southern Europe,ESP,"47,000,000"
Sri Lanka,Asia,Southern Asia,LKA,"33,000,000"
Sudan,Africa,Northern Africa,SDN,"9,600,000"
Suriname,Americas,South America,SUR,"591,000"
Svalbard and Jan Mayen,Europe,Northern Europe,SJM,"4,000,000"
Swaziland,Africa,Southern Africa,SWZ,"1,200,000"
Sweden,Europe,Northern Europe,SWE,"10,700,000"
Switzerland,Europe,Western Europe,CHE,"8,700,000"
Syrian Arab Republic,Asia,Western Asia,SYR,"2,800,000"
"Taiwan, Province of China",Asia,Eastern Asia,TWN,"34,000,000"
Tajikistan,Asia,Central Asia,TJK,"9,500,000"
"Tanzania, United Republic of",Africa,Eastern Africa,TZA,"59,700,000"
Thailand,Asia,South-Eastern Asia,THA,"69,800,000"
Timor-Leste,Asia,South-Eastern Asia,TLS,"1,300,000"
Togo,Africa,Western Africa,TGO,"8,300,000"
Tokelau,Oceania,Polynesia,TKL,"2,000,000"
Tonga,Oceania,Polynesia,TON,"11,500,000"
Trinidad and Tobago,Americas,Caribbean,TTO,"1,900,000"
Tunisia,Africa,Northern Africa,TUN,"125,000,000"
Turkey,Asia,Western Asia,TUR,"84,000,000"
Turkmenistan,Asia,Central Asia,TKM,"6,000,000"
Turks and Caicos Islands,Americas,Caribbean,TCA,"69,800,000"
Tuvalu,Oceania,Polynesia,TUV,"15,000,000"
Uganda,Africa,Eastern Africa,UGA,"45,700,000"
Ukraine,Europe,Eastern Europe,UKR,"9,900,000"
United Arab Emirates,Asia,Western Asia,ARE,"9,900,000"
United Kingdom of Great Britain and Northern Ireland,Europe,Northern Europe,GBR,"68,000,000"
United States of America,Americas,Northern America,USA,"59,700,000"
Uruguay,Americas,South America,URY,"5,100,000"
Uzbekistan,Asia,Central Asia,UZB,"6,000,000"
Vanuatu,Oceania,Melanesia,VUT,"5,900,000"
Venezuela (Bolivarian Republic of),Americas,South America,VEN,"4,900,000"
Viet Nam,Asia,South-Eastern Asia,VNM,"97,000,000"
Virgin Islands (British),Americas,Caribbean,VGB,"5,800,000"
Virgin Islands (U.S.),Americas,Caribbean,VIR,"11,400,000"
Wallis and Futuna,Oceania,Polynesia,WLF,"15,900,000"
Western Sahara,Africa,Northern Africa,ESH,"597,000"
Yemen,Asia,Western Asia,YEM,"5,500,000"
Zambia,Africa,Eastern Africa,ZMB,"213,000,000"
Zimbabwe,Africa,Eastern Africa,ZWE,"19,100,000"

In [9]:
df.loc[0]

KeyError: 0

In [10]:
df.loc['Afghanistan']

continent              Asia
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: Afghanistan, dtype: object

In [11]:
df.iloc[0]

continent              Asia
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: Afghanistan, dtype: object

In [12]:
df.iloc[1]

continent              Europe
sub_region    Northern Europe
code_3                    ALA
Unnamed: 4         5,500,000
Name: Åland Islands, dtype: object

In [13]:
#if we dont want to name it, we use iloc

In [14]:
df.reset_index(inplace = True)

In [15]:
df.set_index('continent', inplace = True)

In [16]:
df

,country,sub_region,code_3,Unnamed: 4
continent,,,,
Asia,Afghanistan,Southern Asia,AFG,"6,900,000"
Europe,Åland Islands,Northern Europe,ALA,"5,500,000"
Europe,Albania,Southern Europe,ALB,"3,300,000"
Africa,Algeria,Northern Africa,DZA,"9,500,000"
Oceania,American Samoa,Polynesia,ASM,"55,000"
Europe,Andorra,Southern Europe,AND,"77,000"
Africa,Angola,Middle Africa,AGO,"54,000,000"
Americas,Anguilla,Caribbean,AIA,"2,100,000"
Americas,Antigua and Barbuda,Caribbean,ATG,"98,000"
Americas,Argentina,South America,ARG,"45,000,000"
Asia,Armenia,Western Asia,ARM,"45,700,000"
Americas,Aruba,Caribbean,ABW,"11,600,000"
Oceania,Australia,Australia and New Zealand,AUS,"36,000,000"
Europe,Austria,Western Europe,AUT,"9,000,000"
Asia,Azerbaijan,Western Asia,AZE,"10,000,000"
Americas,Bahamas,Caribbean,BHS,"7,500,000"
Asia,Bahrain,Western Asia,BHR,"1,900,000"
Asia,Bangladesh,Southern Asia,BGD,"2,500,000"
Americas,Barbados,Caribbean,BRB,"44,000,000"
Europe,Belarus,Eastern Europe,BLR,"9,400,000"
Europe,Belgium,Western Europe,BEL,"12,000,000"
Americas,Belize,Central America,BLZ,"9,000,000"
Africa,Benin,Western Africa,BEN,"17,400,000"
Americas,Bermuda,Northern America,BMU,"64,000"
Asia,Bhutan,Southern Asia,BTN,"771,000"
Americas,Bolivia (Plurinational State of),South America,BOL,"12,900,000"
Americas,"Bonaire, Sint Eustatius and Saba",Caribbean,BES,"4,300,000"
Europe,Bosnia and Herzegovina,Southern Europe,BIH,"5,000,000"
Africa,Botswana,Southern Africa,BWA,"29,000,000"
Americas,Brazil,South America,BRA,"32,700,000"
Asia,Brunei Darussalam,South-Eastern Asia,BRN,"9,400,000"
Europe,Bulgaria,Eastern Europe,BGR,"6,900,000"
Africa,Burkina Faso,Western Africa,BFA,"31,000,000"
Africa,Burundi,Eastern Africa,BDI,"128,000,000"
Africa,Cabo Verde,Western Africa,CPV,"556,000"
Asia,Cambodia,South-Eastern Asia,KHM,"2,200,000"
Africa,Cameroon,Middle Africa,CMR,"38,000,000"
Americas,Canada,Northern America,CAN,"60,000,000"
Americas,Cayman Islands,Caribbean,CYM,"66,000"
Africa,Central African Republic,Middle Africa,CAF,"84,000,000"
Africa,Chad,Middle Africa,TCD,"2,100,000"
Americas,Chile,South America,CHL,"25,000,000"
Asia,China,Eastern Asia,CHN,"1,412,000,000"
Americas,Colombia,South America,COL,"51,000,000"
Africa,Comoros,Eastern Africa,COM,"870,000"
Africa,Congo,Middle Africa,COG,"5,500,000"
Africa,Congo (Democratic Republic of the),Middle Africa,COD,"89,000,000"
Oceania,Cook Islands,Polynesia,COK,"206,000,000"
Americas,Costa Rica,Central America,CRI,"5,100,000"
Africa,Côte d'Ivoire,Western Africa,CIV,"38,000,000"
Europe,Croatia,Southern Europe,HRV,"7,900,000"
Americas,Cuba,Caribbean,CUB,"110,000,000"
Americas,Curaçao,Caribbean,CUW,"2,600,000"
Asia,Cyprus,Western Asia,CYP,"1,200,000"
Europe,Czech Republic,Eastern Europe,CZE,"102,000,000"
Europe,Denmark,Northern Europe,DNK,"5,800,000"
Africa,Djibouti,Eastern Africa,DJI,"988,000"
Americas,Dominica,Caribbean,DMA,"72,000"
Americas,Dominican Republic,Caribbean,DOM,"11,200,000"
Americas,Ecuador,South America,ECU,"2,900,000"
Africa,Egypt,Northern Africa,EGY,"11,300,000"
Americas,El Salvador,Central America,SLV,"6,500,000"
Africa,Equatorial Guinea,Middle Africa,GNQ,"1,700,000"
Africa,Eritrea,Eastern Africa,ERI,"5,100,000"
Europe,Estonia,Northern Europe,EST,"1,300,000"
Africa,Ethiopia,Eastern Africa,ETH,"16,700,000"
Americas,Falkland Islands (Malvinas),South America,FLK,"5,500,000"
Europe,Faroe Islands,Northern Europe,FRO,"49,000"
Oceania,Fiji,Melanesia,FJI,"896,000"
Europe,Finland,Northern Europe,FIN,"5,500,000"
Europe,France,Western Europe,FRA,"67,000,000"
Americas,French Guiana,South America,GUF,"45,000,000"
Oceania,French Polynesia,Polynesia,PYF,"40,000,000"
Africa,Gabon,Middle Africa,GAB,"28,000,000"
Africa,Gambia,Western Africa,GMB,"3,000,000"
Asia,Georgia,Western Asia,GEO,"5,400,000"
Europe,Germany,Western Europe,DEU,"83,200,000"
Africa,Ghana,Western Africa,GHA,"51,000,000"
Europe,Gibraltar,Southern Europe,GIB,"6,500,000"
Europe,Greece,Southern Europe,GRC,"10,800,000"
Americas,Greenland,Northern America,GRL,"56,000"
Americas,Grenada,Caribbean,GRD,"16,700,000"
Americas,Guadeloupe,Caribbean,GLP,"9,000,000"
Oceania,Guam,Micronesia,GUM,"2,800,000"
Americas,Guatemala,Central America,GTM,"21,000,000"
Europe,Guernsey,Northern Europe,GGY,"63,000"
Africa,Guinea,Western Africa,GIN,"18,700,000"
Africa,Guinea-Bissau,Western Africa,GNB,"10,000,000"
Americas,Guyana,South America,GUY,"787,000"
Americas,Haiti,Caribbean,HTI,"114,000,000"
Europe,Holy See,Southern Europe,VAT,800
Americas,Honduras,Central America,HND,"10,000,000"
Asia,Hong Kong,Eastern Asia,HKG,"7,500,000"
Europe,Hungary,Eastern Europe,HUN,"9,600,000"
Europe,Iceland,Northern Europe,ISL,"6,900,000"
Asia,India,Southern Asia,IND,"1,400,000,000"
Asia,Indonesia,South-Eastern Asia,IDN,"4,600,000"
Asia,Iran (Islamic Republic of),Southern Asia,IRN,"84,000,000"
Asia,Iraq,Western Asia,IRQ,"89,000,000"
Europe,Ireland,Northern Europe,IRL,"5,000,000"
Europe,Isle of Man,Northern Europe,IMN,"85,000"
Asia,Israel,Western Asia,ISR,"9,300,000"
Europe,Italy,Southern Europe,ITA,"60,000,000"
Americas,Jamaica,Caribbean,JAM,"3,700,000"
Asia,Japan,Eastern Asia,JPN,"18,000,000"
Europe,Jersey,Northern Europe,JEY,"11,800,000"
Asia,Jordan,Western Asia,JOR,"10,300,000"
Asia,Kazakhstan,Central Asia,KAZ,"22,000,000"
Africa,Kenya,Eastern Africa,KEN,"53,800,000"
Oceania,Kiribati,Micronesia,KIR,"17,600,000"
Asia,Korea (Democratic People's Republic of),Eastern Asia,PRK,"38,000,000"
Asia,Korea (Republic of),Eastern Asia,KOR,"51,600,000"
Asia,Kuwait,Western Asia,KWT,"8,300,000"
Asia,Kyrgyzstan,Central Asia,KGZ,"6,600,000"
Asia,Lao People's Democratic Republic,South-Eastern Asia,LAO,"7,300,000"
Europe,Latvia,Northern Europe,LVA,"10,000,000"
Asia,Lebanon,Western Asia,LBN,"6,800,000"
Africa,Lesotho,Southern Africa,LSO,"27,700,000"
Africa,Liberia,Western Africa,LBR,"5,000,000"
Africa,Libya,Northern Africa,LBY,"6,900,000"
Europe,Liechtenstein,Western Europe,LIE,"68,000,000"
Europe,Lithuania,Northern Europe,LTU,"3,500,000"
Europe,Luxembourg,Western Europe,LUX,"633,000"
Asia,Macao,Eastern Asia,MAC,"650,000"
Europe,Macedonia (the former Yugoslav Republic of),Southern Europe,MKD,"26,000,000"
Africa,Madagascar,Eastern Africa,MDG,"4,300,000"
Africa,Malawi,Eastern Africa,MWI,"25,800,000"
Asia,Malaysia,South-Eastern Asia,MYS,"53,800,000"
Asia,Maldives,Southern Asia,MDV,"540,000"
Africa,Mali,Western Africa,MLI,"30,000,000"
Europe,Malta,Southern Europe,MLT,"97,000,000"
Oceania,Marshall Islands,Micronesia,MHL,"59,000"
Americas,Martinique,Caribbean,MTQ,"6,900,000"
Africa,Mauritania,Western Africa,MRT,"83,200,000"
Africa,Mauritius,Eastern Africa,MUS,"1,300,000"
Africa,Mayotte,Eastern Africa,MYT,"4,800,000"
Americas,Mexico,Central America,MEX,"18,400,000"
Oceania,Micronesia (Federated States of),Micronesia,FSM,"164,000,000"
Europe,Moldova (Republic of),Eastern Europe,MDA,"3,300,000"
Europe,Monaco,Western Europe,MCO,"7,100,000"
Asia,Mongolia,Eastern Asia,MNG,"5,000,000"
Europe,Montenegro,Southern Europe,MNE,"622,000"
Americas,Montserrat,Caribbean,MSR,"5,000"
Africa,Morocco,Northern Africa,MAR,"6,800,000"
Africa,Mozambique,Eastern Africa,MOZ,"51,600,000"
Asia,Myanmar,South-Eastern Asia,MMR,"54,000,000"
Africa,Namibia,Southern Africa,NAM,"3,200,000"
Oceania,Nauru,Micronesia,NRU,"144,000,000"
Asia,Nepal,Southern Asia,NPL,"44,000,000"
Europe,Netherlands,Western Europe,NLD,"2,800,000"
Oceania,New Caledonia,Melanesia,NCL,"44,000,000"
Oceania,New Zealand,Australia and New Zealand,NZL,"84,000,000"
Americas,Nicaragua,Central America,NIC,"6,600,000"
Africa,Niger,Western Africa,NER,"35,000,000"
Africa,Nigeria,Western Africa,NGA,"31,000,000"
Oceania,Niue,Polynesia,NIU,"2,400,000"
Oceania,Norfolk Island,Australia and New Zealand,NFK,"20,300,000"
Oceania,Northern Mariana Islands,Micronesia,MNP,"58,000"
Europe,Norway,Northern Europe,NOR,"5,400,000"
Asia,Oman,Western Asia,OMN,"5,000,000"
Asia,Pakistan,Southern Asia,PAK,"331,000,000"
Oceania,Palau,Micronesia,PLW,"220,000,000"
Asia,"Palestine, State of",Western Asia,PSE,"5,100,000"
Americas,Panama,Central America,PAN,"8,700,000"
Oceania,Papua New Guinea,Melanesia,PNG,"9,000,000"
Americas,Paraguay,South America,PRY,"7,100,000"
Americas,Peru,South America,PER,"59,000,000"
Asia,Philippines,South-Eastern Asia,PHL,"13,100,000"
Oceania,Pitcairn,Polynesia,PCN,"50,000,000"
Europe,Poland,Eastern Europe,POL,"67,000,000"
Europe,Portugal,Southern Europe,PRT,"10,400,000"
Americas,Puerto Rico,Caribbean,PRI,"47,000,000"
Asia,Qatar,Western Asia,QAT,"3,500,000"
Africa,Réunion,Eastern Africa,REU,"859,000"
Europe,Romania,Eastern Europe,ROU,"24,000,000"
Europe,Russian Federation,Eastern Europe,RUS,"19,000,000"
Africa,Rwanda,Eastern Africa,RWA,"17,500,000"
Americas,Saint Barthélemy,Caribbean,BLM,"9,900"
Africa,"Saint Helena, Ascension and Tristan da Cunha",Western Africa,SHN,"6,000"
Americas,Saint Kitts and Nevis,Caribbean,KNA,"53,000"
Americas,Saint Lucia,Caribbean,LCA,"23,800,000"
Americas,Saint Martin (French part),Caribbean,MAF,"7,300,000"
Americas,Saint Pierre and Miquelon,Northern America,SPM,"5,700"
Americas,Saint Vincent and the Grenadines,Caribbean,VCT,"16,400,000"
Oceania,Samoa,Polynesia,WSM,"26,000,000"
Europe,San Marino,Southern Europe,SMR,"6,600,000"
Africa,Sao Tome and Principe,Middle Africa,STP,"33,000,000"
Asia,Saudi Arabia,Western Asia,SAU,"6,600,000"
Africa,Senegal,Western Africa,SEN,"2,300,000"
Europe,Serbia,Southern Europe,SRB,"6,900,000"
Africa,Seychelles,Eastern Africa,SYC,"98,000"
Africa,Sierra Leone,Western Africa,SLE,"7,900,000"
Asia,Singapore,South-Eastern Asia,SGP,"5,900,000"
Americas,Sint Maarten (Dutch part),Caribbean,SXM,"9,300,000"
Europe,Slovakia,Eastern Europe,SVK,"5,500,000"
Europe,Slovenia,Southern Europe,SVN,"276,000,000"
Oceania,Solomon Islands,Melanesia,SLB,"686,000"
Africa,Somalia,Eastern Africa,SOM,"19,100,000"
Africa,South Africa,Southern Africa,ZAF,"59,000,000"
Africa,South Sudan,Eastern Africa,SSD,"11,900,000"
Europe,Spain,Southern Europe,ESP,"47,000,000"
Asia,Sri Lanka,Southern Asia,LKA,"33,000,000"
Africa,Sudan,Northern Africa,SDN,"9,600,000"
Americas,Suriname,South America,SUR,"591,000"
Europe,Svalbard and Jan Mayen,Northern Europe,SJM,"4,000,000"
Africa,Swaziland,Southern Africa,SWZ,"1,200,000"
Europe,Sweden,Northern Europe,SWE,"10,700,000"
Europe,Switzerland,Western Europe,CHE,"8,700,000"
Asia,Syrian Arab Republic,Western Asia,SYR,"2,800,000"
Asia,"Taiwan, Province of China",Eastern Asia,TWN,"34,000,000"
Asia,Tajikistan,Central Asia,TJK,"9,500,000"
Africa,"Tanzania, United Republic of",Eastern Africa,TZA,"59,700,000"
Asia,Thailand,South-Eastern Asia,THA,"69,800,000"
Asia,Timor-Leste,South-Eastern Asia,TLS,"1,300,000"
Africa,Togo,Western Africa,TGO,"8,300,000"
Oceania,Tokelau,Polynesia,TKL,"2,000,000"
Oceania,Tonga,Polynesia,TON,"11,500,000"
Americas,Trinidad and Tobago,Caribbean,TTO,"1,900,000"
Africa,Tunisia,Northern Africa,TUN,"125,000,000"
Asia,Turkey,Western Asia,TUR,"84,000,000"
Asia,Turkmenistan,Central Asia,TKM,"6,000,000"
Americas,Turks and Caicos Islands,Caribbean,TCA,"69,800,000"
Oceania,Tuvalu,Polynesia,TUV,"15,000,000"
Africa,Uganda,Eastern Africa,UGA,"45,700,000"
Europe,Ukraine,Eastern Europe,UKR,"9,900,000"
Asia,United Arab Emirates,Western Asia,ARE,"9,900,000"
Europe,United Kingdom of Great Britain and Northern I...,Northern Europe,GBR,"68,000,000"
Americas,United States of America,Northern America,USA,"59,700,000"
Americas,Uruguay,South America,URY,"5,100,000"
Asia,Uzbekistan,Central Asia,UZB,"6,000,000"
Oceania,Vanuatu,Melanesia,VUT,"5,900,000"
Americas,Venezuela (Bolivarian Republic of),South America,VEN,"4,900,000"
Asia,Viet Nam,South-Eastern Asia,VNM,"97,000,000"
Americas,Virgin Islands (British),Caribbean,VGB,"5,800,000"
Americas,Virgin Islands (U.S.),Caribbean,VIR,"11,400,000"
Oceania,Wallis and Futuna,Polynesia,WLF,"15,900,000"
Africa,Western Sahara,Northern Africa,ESH,"597,000"
Asia,Yemen,Western Asia,YEM,"5,500,000"
Africa,Zambia,Eastern Africa,ZMB,"213,000,000"
Africa,Zimbabwe,Eastern Africa,ZWE,"19,100,000"

In [17]:
df.loc['Asia']

,country,sub_region,code_3,Unnamed: 4
continent,,,,
Asia,Afghanistan,Southern Asia,AFG,"6,900,000"
Asia,Armenia,Western Asia,ARM,"45,700,000"
Asia,Azerbaijan,Western Asia,AZE,"10,000,000"
Asia,Bahrain,Western Asia,BHR,"1,900,000"
Asia,Bangladesh,Southern Asia,BGD,"2,500,000"
Asia,Bhutan,Southern Asia,BTN,"771,000"
Asia,Brunei Darussalam,South-Eastern Asia,BRN,"9,400,000"
Asia,Cambodia,South-Eastern Asia,KHM,"2,200,000"
Asia,China,Eastern Asia,CHN,"1,412,000,000"
Asia,Cyprus,Western Asia,CYP,"1,200,000"
Asia,Georgia,Western Asia,GEO,"5,400,000"
Asia,Hong Kong,Eastern Asia,HKG,"7,500,000"
Asia,India,Southern Asia,IND,"1,400,000,000"
Asia,Indonesia,South-Eastern Asia,IDN,"4,600,000"
Asia,Iran (Islamic Republic of),Southern Asia,IRN,"84,000,000"
Asia,Iraq,Western Asia,IRQ,"89,000,000"
Asia,Israel,Western Asia,ISR,"9,300,000"
Asia,Japan,Eastern Asia,JPN,"18,000,000"
Asia,Jordan,Western Asia,JOR,"10,300,000"
Asia,Kazakhstan,Central Asia,KAZ,"22,000,000"
Asia,Korea (Democratic People's Republic of),Eastern Asia,PRK,"38,000,000"
Asia,Korea (Republic of),Eastern Asia,KOR,"51,600,000"
Asia,Kuwait,Western Asia,KWT,"8,300,000"
Asia,Kyrgyzstan,Central Asia,KGZ,"6,600,000"
Asia,Lao People's Democratic Republic,South-Eastern Asia,LAO,"7,300,000"
Asia,Lebanon,Western Asia,LBN,"6,800,000"
Asia,Macao,Eastern Asia,MAC,"650,000"
Asia,Malaysia,South-Eastern Asia,MYS,"53,800,000"
Asia,Maldives,Southern Asia,MDV,"540,000"
Asia,Mongolia,Eastern Asia,MNG,"5,000,000"
Asia,Myanmar,South-Eastern Asia,MMR,"54,000,000"
Asia,Nepal,Southern Asia,NPL,"44,000,000"
Asia,Oman,Western Asia,OMN,"5,000,000"
Asia,Pakistan,Southern Asia,PAK,"331,000,000"
Asia,"Palestine, State of",Western Asia,PSE,"5,100,000"
Asia,Philippines,South-Eastern Asia,PHL,"13,100,000"
Asia,Qatar,Western Asia,QAT,"3,500,000"
Asia,Saudi Arabia,Western Asia,SAU,"6,600,000"
Asia,Singapore,South-Eastern Asia,SGP,"5,900,000"
Asia,Sri Lanka,Southern Asia,LKA,"33,000,000"
Asia,Syrian Arab Republic,Western Asia,SYR,"2,800,000"
Asia,"Taiwan, Province of China",Eastern Asia,TWN,"34,000,000"
Asia,Tajikistan,Central Asia,TJK,"9,500,000"
Asia,Thailand,South-Eastern Asia,THA,"69,800,000"
Asia,Timor-Leste,South-Eastern Asia,TLS,"1,300,000"
Asia,Turkey,Western Asia,TUR,"84,000,000"
Asia,Turkmenistan,Central Asia,TKM,"6,000,000"
Asia,United Arab Emirates,Western Asia,ARE,"9,900,000"
Asia,Uzbekistan,Central Asia,UZB,"6,000,000"
Asia,Viet Nam,South-Eastern Asia,VNM,"97,000,000"
Asia,Yemen,Western Asia,YEM,"5,500,000"

In [18]:
df.iloc[0]

country         Afghanistan
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: Asia, dtype: object

In [19]:
df.reset_index(inplace = True)

In [21]:
df_continent = df.set_index(['continent', 'sub_region'])

In [22]:
df_continent

                                                                               country  \
continent sub_region
Asia      Southern Asia                                                    Afghanistan
Europe    Northern Europe                                                Åland Islands
          Southern Europe                                                      Albania
Africa    Northern Africa                                                      Algeria
Oceania   Polynesia                                                     American Samoa
Europe    Southern Europe                                                      Andorra
Africa    Middle Africa                                                         Angola
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          South America                                                      Argentina
Asia      Western Asia                                                         Armenia
Americas  Caribbean                                                              Aruba
Oceania   Australia and New Zealand                                          Australia
Europe    Western Europe                                                       Austria
Asia      Western Asia                                                      Azerbaijan
Americas  Caribbean                                                            Bahamas
Asia      Western Asia                                                         Bahrain
          Southern Asia                                                     Bangladesh
Americas  Caribbean                                                           Barbados
Europe    Eastern Europe                                                       Belarus
          Western Europe                                                       Belgium
Americas  Central America                                                       Belize
Africa    Western Africa                                                         Benin
Americas  Northern America                                                     Bermuda
Asia      Southern Asia                                                         Bhutan
Americas  South America                               Bolivia (Plurinational State of)
          Caribbean                                   Bonaire, Sint Eustatius and Saba
Europe    Southern Europe                                       Bosnia and Herzegovina
Africa    Southern Africa                                                     Botswana
Americas  South America                                                         Brazil
Asia      South-Eastern Asia                                         Brunei Darussalam
Europe    Eastern Europe                                                      Bulgaria
Africa    Western Africa                                                  Burkina Faso
          Eastern Africa                                                       Burundi
          Western Africa                                                    Cabo Verde
Asia      South-Eastern Asia                                                  Cambodia
Africa    Middle Africa                                                       Cameroon
Americas  Northern America                                                      Canada
          Caribbean                                                     Cayman Islands
Africa    Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
Americas  South America                                                          Chile
Asia      Eastern Asia                                                           China
Americas  South America                                                       Colombia
Africa    Eastern Africa                                                       Comoros
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
Oceania   Polynesia                                                       Cook Islands
Americas  Central America                                                   Costa Rica
Africa    Western Africa                                                 Côte d'Ivoire
Europe    Southern Europe                                                      Croatia
Americas  Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
Asia      Western Asia                                                          Cyprus
Europe    Eastern Europe                                                Czech Republic
          Northern Europe                                                      Denmark
Africa    Eastern Africa                                                      Djibouti
Americas  Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          South America                                                        Ecuador
Africa    Northern Africa                                                        Egypt
Americas  Central America                                                  El Salvador
Africa    Middle Africa                                              Equatorial Guinea
          Eastern Africa                                                       Eritrea
Europe    Northern Europe                                                      Estonia
Africa    Eastern Africa                                                      Ethiopia
Americas  South America                                    Falkland Islands (Malvinas)
Europe    Northern Europe                                                Faroe Islands
Oceania   Melanesia                                                               Fiji
Europe    Northern Europe                                                      Finland
          Western Europe                                                        France
Americas  South America                                                  French Guiana
Oceania   Polynesia                                                   French Polynesia
Africa    Middle Africa                                                          Gabon
          Western Africa                                                        Gambia
Asia      Western Asia                                                         Georgia
Europe    Western Europe                                                       Germany
Africa    Western Africa                                                         Ghana
Europe    Southern Europe                                                    Gibraltar
          Southern Europe                                                       Greece
Americas  Northern America                                                   Greenland
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
Oceania   Micronesia                                                              Guam
Americas  Central America                                                    Guatemala
Europe    Northern Europe                                                     Guernsey
Africa    Western Africa                                                        Guinea
          Western Africa                                                 Guinea-Bissau
Americas  South America                                                         Guyana
          Caribbean                                                              Haiti
Europe    Southern Europe                                                     Holy See
Americas  Central America                                                     Honduras
Asia      Eastern Asia                                                       Hong Kong
Europe    Eastern Europe                                                       Hungary
          Northern Europe                                                      Iceland
Asia      Southern Asia                                                          India
          South-Eastern Asia                                                 Indonesia
          Southern Asia                                     Iran (Islamic Republic of)
          Western Asia                                                            Iraq
Europe    Northern Europe                                                      Ireland
          Northern Europe                                                  Isle of Man
Asia      Western Asia                                                          Israel
Europe    Southern Europe                                                        Italy
Americas  Caribbean                                                            Jamaica
Asia      Eastern Asia                                                           Japan
Europe    Northern Europe                                                       Jersey
Asia      Western Asia                                                          Jordan
          Central Asia                                                      Kazakhstan
Africa    Eastern Africa                                                         Kenya
Oceania   Micronesia                                                          Kiribati
Asia      Eastern Asia                         Korea (Democratic People's Republic of)
          Eastern Asia                                             Korea (Republic of)
          Western Asia                                                          Kuwait
          Central Asia                                                      Kyrgyzstan
          South-Eastern Asia                          Lao People's Democratic Republic
Europe    Northern Europe                                                       Latvia
Asia      Western Asia                                                         Lebanon
Africa    Southern Africa                                                      Lesotho
          Western Africa                                                       Liberia
          Northern Africa                                                        Libya
Europe    Western Europe                                                 Liechtenstein
          Northern Europe                                                    Lithuania
          Western Europe                                                    Luxembourg
Asia      Eastern Asia                                                           Macao
Europe    Southern Europe                  Macedonia (the former Yugoslav Republic of)
Africa    Eastern Africa                                                    Madagascar
          Eastern Africa                                                        Malawi
Asia      South-Eastern Asia                                                  Malaysia
          Southern Asia                                                       Maldives
Africa    Western Africa                                                          Mali
Europe    Southern Europe                                                        Malta
Oceania   Micronesia                                                  Marshall Islands
Americas  Caribbean                                                         Martinique
Africa    Western Africa                                                    Mauritania
          Eastern Africa                                                     Mauritius
          Eastern Africa                                                       Mayotte
Americas  Central America                                                       Mexico
Oceania   Micronesia                                  Micronesia (Federated States of)
Europe    Eastern Europe                                         Moldova (Republic of)
          Western Europe                                                        Monaco
Asia      Eastern Asia                                                        Mongolia
Europe    Southern Europe                                                   Montenegro
Americas  Caribbean                                                         Montserrat
Africa    Northern Africa                                                      Morocco
          Eastern Africa                                                    Mozambique
Asia      South-Eastern Asia                                                   Myanmar
Africa    Southern Africa                                                      Namibia
Oceania   Micronesia                                                             Nauru
Asia      Southern Asia                                                          Nepal
Europe    Western Europe                                                   Netherlands
Oceania   Melanesia                                                      New Caledonia
          Australia and New Zealand                                        New Zealand
Americas  Central America                                                    Nicaragua
Africa    Western Africa                                                         Niger
          Western Africa                                                       Nigeria
Oceania   Polynesia                                                               Niue
          Australia and New Zealand                                     Norfolk Island
          Micronesia                                          Northern Mariana Islands
Europe    Northern Europe                                                       Norway
Asia      Western Asia                                                            Oman
          Southern Asia                                                       Pakistan
Oceania   Micronesia                                                             Palau
Asia      Western Asia                                             Palestine, State of
Americas  Central America                                                       Panama
Oceania   Melanesia                                                   Papua New Guinea
Americas  South America                                                       Paraguay
          South America                                                           Peru
Asia      South-Eastern Asia                                               Philippines
Oceania   Polynesia                                                           Pitcairn
Europe    Eastern Europe                                                        Poland
          Southern Europe                                                     Portugal
Americas  Caribbean                                                        Puerto Rico
Asia      Western Asia                                                           Qatar
Africa    Eastern Africa                                                       Réunion
Europe    Eastern Europe                                                       Romania
          Eastern Europe                                            Russian Federation
Africa    Eastern Africa                                                        Rwanda
Americas  Caribbean                                                   Saint Barthélemy
Africa    Western Africa                  Saint Helena, Ascension and Tristan da Cunha
Americas  Caribbean                                              Saint Kitts and Nevis
          Caribbean                                                        Saint Lucia
          Caribbean                                         Saint Martin (French part)
          Northern America                                   Saint Pierre and Miquelon
          Caribbean                                   Saint Vincent and the Grenadines
Oceania   Polynesia                                                              Samoa
Europe    Southern Europe                                                   San Marino
Africa    Middle Africa                                          Sao Tome and Principe
Asia      Western Asia                                                    Saudi Arabia
Africa    Western Africa                                                       Senegal
Europe    Southern Europe                                                       Serbia
Africa    Eastern Africa                                                    Seychelles
          Western Africa                                                  Sierra Leone
Asia      South-Eastern Asia                                                 Singapore
Americas  Caribbean                                          Sint Maarten (Dutch part)
Europe    Eastern Europe                                                      Slovakia
          Southern Europe                                                     Slovenia
Oceania   Melanesia                                                    Solomon Islands
Africa    Eastern Africa                                                       Somalia
          Southern Africa                                                 South Africa
          Eastern Africa                                                   South Sudan
Europe    Southern Europe                                                        Spain
Asia      Southern Asia                                                      Sri Lanka
Africa    Northern Africa                                                        Sudan
Americas  South America                                                       Suriname
Europe    Northern Europe                                       Svalbard and Jan Mayen
Africa    Southern Africa                                                    Swaziland
Europe    Northern Europe                                                       Sweden
          Western Europe                                                   Switzerland
Asia      Western Asia                                            Syrian Arab Republic
          Eastern Asia                                       Taiwan, Province of China
          Central Asia                                                      Tajikistan
Africa    Eastern Africa                                  Tanzania, United Republic of
Asia      South-Eastern Asia                                                  Thailand
          South-Eastern Asia                                               Timor-Leste
Africa    Western Africa                                                          Togo
Oceania   Polynesia                                                            Tokelau
          Polynesia                                                              Tonga
Americas  Caribbean                                                Trinidad and Tobago
Africa    Northern Africa                                                      Tunisia
Asia      Western Asia                                                          Turkey
          Central Asia                                                    Turkmenistan
Americas  Caribbean                                           Turks and Caicos Islands
Oceania   Polynesia                                                             Tuvalu
Africa    Eastern Africa                                                        Uganda
Europe    Eastern Europe                                                       Ukraine
Asia      Western Asia                                            United Arab Emirates
Europe    Northern Europe            United Kingdom of Great Britain and Northern I...
Americas  Northern America                                    United States of America

In [23]:
df_continent.loc['Asia','Southern Asia']

C:\Users\nazom\AppData\Local\Temp/ipykernel_12044/389584776.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_continent.loc['Asia','Southern Asia']

                                            country code_3       Unnamed: 4
continent sub_region
Asia      Southern Asia                 Afghanistan    AFG       6,900,000
          Southern Asia                  Bangladesh    BGD       2,500,000
          Southern Asia                      Bhutan    BTN         771,000
          Southern Asia                       India    IND   1,400,000,000
          Southern Asia  Iran (Islamic Republic of)    IRN      84,000,000
          Southern Asia                    Maldives    MDV         540,000
          Southern Asia                       Nepal    NPL      44,000,000
          Southern Asia                    Pakistan    PAK     331,000,000
          Southern Asia                   Sri Lanka    LKA      33,000,000

In [25]:
df_continent.iloc[0]

country       Afghanistan
code_3                AFG
Unnamed: 4     6,900,000
Name: (Asia, Southern Asia), dtype: object

In [26]:
df_continent.iloc[0,0]

'Afghanistan'

In [27]:
#Reordering and sorting indexes

In [28]:
df.reset_index(inplace = True)

In [29]:
df

,index,continent,country,sub_region,code_3,Unnamed: 4
0,0,Asia,Afghanistan,Southern Asia,AFG,"6,900,000"
1,1,Europe,Åland Islands,Northern Europe,ALA,"5,500,000"
2,2,Europe,Albania,Southern Europe,ALB,"3,300,000"
3,3,Africa,Algeria,Northern Africa,DZA,"9,500,000"
4,4,Oceania,American Samoa,Polynesia,ASM,"55,000"
5,5,Europe,Andorra,Southern Europe,AND,"77,000"
6,6,Africa,Angola,Middle Africa,AGO,"54,000,000"
7,7,Americas,Anguilla,Caribbean,AIA,"2,100,000"
8,8,Americas,Antigua and Barbuda,Caribbean,ATG,"98,000"
9,9,Americas,Argentina,South America,ARG,"45,000,000"
10,10,Asia,Armenia,Western Asia,ARM,"45,700,000"
11,11,Americas,Aruba,Caribbean,ABW,"11,600,000"
12,12,Oceania,Australia,Australia and New Zealand,AUS,"36,000,000"
13,13,Europe,Austria,Western Europe,AUT,"9,000,000"
14,14,Asia,Azerbaijan,Western Asia,AZE,"10,000,000"
15,15,Americas,Bahamas,Caribbean,BHS,"7,500,000"
16,16,Asia,Bahrain,Western Asia,BHR,"1,900,000"
17,17,Asia,Bangladesh,Southern Asia,BGD,"2,500,000"
18,18,Americas,Barbados,Caribbean,BRB,"44,000,000"
19,19,Europe,Belarus,Eastern Europe,BLR,"9,400,000"
20,20,Europe,Belgium,Western Europe,BEL,"12,000,000"
21,21,Americas,Belize,Central America,BLZ,"9,000,000"
22,22,Africa,Benin,Western Africa,BEN,"17,400,000"
23,23,Americas,Bermuda,Northern America,BMU,"64,000"
24,24,Asia,Bhutan,Southern Asia,BTN,"771,000"
25,25,Americas,Bolivia (Plurinational State of),South America,BOL,"12,900,000"
26,26,Americas,"Bonaire, Sint Eustatius and Saba",Caribbean,BES,"4,300,000"
27,27,Europe,Bosnia and Herzegovina,Southern Europe,BIH,"5,000,000"
28,28,Africa,Botswana,Southern Africa,BWA,"29,000,000"
29,29,Americas,Brazil,South America,BRA,"32,700,000"
30,30,Asia,Brunei Darussalam,South-Eastern Asia,BRN,"9,400,000"
31,31,Europe,Bulgaria,Eastern Europe,BGR,"6,900,000"
32,32,Africa,Burkina Faso,Western Africa,BFA,"31,000,000"
33,33,Africa,Burundi,Eastern Africa,BDI,"128,000,000"
34,34,Africa,Cabo Verde,Western Africa,CPV,"556,000"
35,35,Asia,Cambodia,South-Eastern Asia,KHM,"2,200,000"
36,36,Africa,Cameroon,Middle Africa,CMR,"38,000,000"
37,37,Americas,Canada,Northern America,CAN,"60,000,000"
38,38,Americas,Cayman Islands,Caribbean,CYM,"66,000"
39,39,Africa,Central African Republic,Middle Africa,CAF,"84,000,000"
40,40,Africa,Chad,Middle Africa,TCD,"2,100,000"
41,41,Americas,Chile,South America,CHL,"25,000,000"
42,42,Asia,China,Eastern Asia,CHN,"1,412,000,000"
43,43,Americas,Colombia,South America,COL,"51,000,000"
44,44,Africa,Comoros,Eastern Africa,COM,"870,000"
45,45,Africa,Congo,Middle Africa,COG,"5,500,000"
46,46,Africa,Congo (Democratic Republic of the),Middle Africa,COD,"89,000,000"
47,47,Oceania,Cook Islands,Polynesia,COK,"206,000,000"
48,48,Americas,Costa Rica,Central America,CRI,"5,100,000"
49,49,Africa,Côte d'Ivoire,Western Africa,CIV,"38,000,000"
50,50,Europe,Croatia,Southern Europe,HRV,"7,900,000"
51,51,Americas,Cuba,Caribbean,CUB,"110,000,000"
52,52,Americas,Curaçao,Caribbean,CUW,"2,600,000"
53,53,Asia,Cyprus,Western Asia,CYP,"1,200,000"
54,54,Europe,Czech Republic,Eastern Europe,CZE,"102,000,000"
55,55,Europe,Denmark,Northern Europe,DNK,"5,800,000"
56,56,Africa,Djibouti,Eastern Africa,DJI,"988,000"
57,57,Americas,Dominica,Caribbean,DMA,"72,000"
58,58,Americas,Dominican Republic,Caribbean,DOM,"11,200,000"
59,59,Americas,Ecuador,South America,ECU,"2,900,000"
60,60,Africa,Egypt,Northern Africa,EGY,"11,300,000"
61,61,Americas,El Salvador,Central America,SLV,"6,500,000"
62,62,Africa,Equatorial Guinea,Middle Africa,GNQ,"1,700,000"
63,63,Africa,Eritrea,Eastern Africa,ERI,"5,100,000"
64,64,Europe,Estonia,Northern Europe,EST,"1,300,000"
65,65,Africa,Ethiopia,Eastern Africa,ETH,"16,700,000"
66,66,Americas,Falkland Islands (Malvinas),South America,FLK,"5,500,000"
67,67,Europe,Faroe Islands,Northern Europe,FRO,"49,000"
68,68,Oceania,Fiji,Melanesia,FJI,"896,000"
69,69,Europe,Finland,Northern Europe,FIN,"5,500,000"
70,70,Europe,France,Western Europe,FRA,"67,000,000"
71,71,Americas,French Guiana,South America,GUF,"45,000,000"
72,72,Oceania,French Polynesia,Polynesia,PYF,"40,000,000"
73,73,Africa,Gabon,Middle Africa,GAB,"28,000,000"
74,74,Africa,Gambia,Western Africa,GMB,"3,000,000"
75,75,Asia,Georgia,Western Asia,GEO,"5,400,000"
76,76,Europe,Germany,Western Europe,DEU,"83,200,000"
77,77,Africa,Ghana,Western Africa,GHA,"51,000,000"
78,78,Europe,Gibraltar,Southern Europe,GIB,"6,500,000"
79,79,Europe,Greece,Southern Europe,GRC,"10,800,000"
80,80,Americas,Greenland,Northern America,GRL,"56,000"
81,81,Americas,Grenada,Caribbean,GRD,"16,700,000"
82,82,Americas,Guadeloupe,Caribbean,GLP,"9,000,000"
83,83,Oceania,Guam,Micronesia,GUM,"2,800,000"
84,84,Americas,Guatemala,Central America,GTM,"21,000,000"
85,85,Europe,Guernsey,Northern Europe,GGY,"63,000"
86,86,Africa,Guinea,Western Africa,GIN,"18,700,000"
87,87,Africa,Guinea-Bissau,Western Africa,GNB,"10,000,000"
88,88,Americas,Guyana,South America,GUY,"787,000"
89,89,Americas,Haiti,Caribbean,HTI,"114,000,000"
90,90,Europe,Holy See,Southern Europe,VAT,800
91,91,Americas,Honduras,Central America,HND,"10,000,000"
92,92,Asia,Hong Kong,Eastern Asia,HKG,"7,500,000"
93,93,Europe,Hungary,Eastern Europe,HUN,"9,600,000"
94,94,Europe,Iceland,Northern Europe,ISL,"6,900,000"
95,95,Asia,India,Southern Asia,IND,"1,400,000,000"
96,96,Asia,Indonesia,South-Eastern Asia,IDN,"4,600,000"
97,97,Asia,Iran (Islamic Republic of),Southern Asia,IRN,"84,000,000"
98,98,Asia,Iraq,Western Asia,IRQ,"89,000,000"
99,99,Europe,Ireland,Northern Europe,IRL,"5,000,000"
100,100,Europe,Isle of Man,Northern Europe,IMN,"85,000"
101,101,Asia,Israel,Western Asia,ISR,"9,300,000"
102,102,Europe,Italy,Southern Europe,ITA,"60,000,000"
103,103,Americas,Jamaica,Caribbean,JAM,"3,700,000"
104,104,Asia,Japan,Eastern Asia,JPN,"18,000,000"
105,105,Europe,Jersey,Northern Europe,JEY,"11,800,000"
106,106,Asia,Jordan,Western Asia,JOR,"10,300,000"
107,107,Asia,Kazakhstan,Central Asia,KAZ,"22,000,000"
108,108,Africa,Kenya,Eastern Africa,KEN,"53,800,000"
109,109,Oceania,Kiribati,Micronesia,KIR,"17,600,000"
110,110,Asia,Korea (Democratic People's Republic of),Eastern Asia,PRK,"38,000,000"
111,111,Asia,Korea (Republic of),Eastern Asia,KOR,"51,600,000"
112,112,Asia,Kuwait,Western Asia,KWT,"8,300,000"
113,113,Asia,Kyrgyzstan,Central Asia,KGZ,"6,600,000"
114,114,Asia,Lao People's Democratic Republic,South-Eastern Asia,LAO,"7,300,000"
115,115,Europe,Latvia,Northern Europe,LVA,"10,000,000"
116,116,Asia,Lebanon,Western Asia,LBN,"6,800,000"
117,117,Africa,Lesotho,Southern Africa,LSO,"27,700,000"
118,118,Africa,Liberia,Western Africa,LBR,"5,000,000"
119,119,Africa,Libya,Northern Africa,LBY,"6,900,000"
120,120,Europe,Liechtenstein,Western Europe,LIE,"68,000,000"
121,121,Europe,Lithuania,Northern Europe,LTU,"3,500,000"
122,122,Europe,Luxembourg,Western Europe,LUX,"633,000"
123,123,Asia,Macao,Eastern Asia,MAC,"650,000"
124,124,Europe,Macedonia (the former Yugoslav Republic of),Southern Europe,MKD,"26,000,000"
125,125,Africa,Madagascar,Eastern Africa,MDG,"4,300,000"
126,126,Africa,Malawi,Eastern Africa,MWI,"25,800,000"
127,127,Asia,Malaysia,South-Eastern Asia,MYS,"53,800,000"
128,128,Asia,Maldives,Southern Asia,MDV,"540,000"
129,129,Africa,Mali,Western Africa,MLI,"30,000,000"
130,130,Europe,Malta,Southern Europe,MLT,"97,000,000"
131,131,Oceania,Marshall Islands,Micronesia,MHL,"59,000"
132,132,Americas,Martinique,Caribbean,MTQ,"6,900,000"
133,133,Africa,Mauritania,Western Africa,MRT,"83,200,000"
134,134,Africa,Mauritius,Eastern Africa,MUS,"1,300,000"
135,135,Africa,Mayotte,Eastern Africa,MYT,"4,800,000"
136,136,Americas,Mexico,Central America,MEX,"18,400,000"
137,137,Oceania,Micronesia (Federated States of),Micronesia,FSM,"164,000,000"
138,138,Europe,Moldova (Republic of),Eastern Europe,MDA,"3,300,000"
139,139,Europe,Monaco,Western Europe,MCO,"7,100,000"
140,140,Asia,Mongolia,Eastern Asia,MNG,"5,000,000"
141,141,Europe,Montenegro,Southern Europe,MNE,"622,000"
142,142,Americas,Montserrat,Caribbean,MSR,"5,000"
143,143,Africa,Morocco,Northern Africa,MAR,"6,800,000"
144,144,Africa,Mozambique,Eastern Africa,MOZ,"51,600,000"
145,145,Asia,Myanmar,South-Eastern Asia,MMR,"54,000,000"
146,146,Africa,Namibia,Southern Africa,NAM,"3,200,000"
147,147,Oceania,Nauru,Micronesia,NRU,"144,000,000"
148,148,Asia,Nepal,Southern Asia,NPL,"44,000,000"
149,149,Europe,Netherlands,Western Europe,NLD,"2,800,000"
150,150,Oceania,New Caledonia,Melanesia,NCL,"44,000,000"
151,151,Oceania,New Zealand,Australia and New Zealand,NZL,"84,000,000"
152,152,Americas,Nicaragua,Central America,NIC,"6,600,000"
153,153,Africa,Niger,Western Africa,NER,"35,000,000"
154,154,Africa,Nigeria,Western Africa,NGA,"31,000,000"
155,155,Oceania,Niue,Polynesia,NIU,"2,400,000"
156,156,Oceania,Norfolk Island,Australia and New Zealand,NFK,"20,300,000"
157,157,Oceania,Northern Mariana Islands,Micronesia,MNP,"58,000"
158,158,Europe,Norway,Northern Europe,NOR,"5,400,000"
159,159,Asia,Oman,Western Asia,OMN,"5,000,000"
160,160,Asia,Pakistan,Southern Asia,PAK,"331,000,000"
161,161,Oceania,Palau,Micronesia,PLW,"220,000,000"
162,162,Asia,"Palestine, State of",Western Asia,PSE,"5,100,000"
163,163,Americas,Panama,Central America,PAN,"8,700,000"
164,164,Oceania,Papua New Guinea,Melanesia,PNG,"9,000,000"
165,165,Americas,Paraguay,South America,PRY,"7,100,000"
166,166,Americas,Peru,South America,PER,"59,000,000"
167,167,Asia,Philippines,South-Eastern Asia,PHL,"13,100,000"
168,168,Oceania,Pitcairn,Polynesia,PCN,"50,000,000"
169,169,Europe,Poland,Eastern Europe,POL,"67,000,000"
170,170,Europe,Portugal,Southern Europe,PRT,"10,400,000"
171,171,Americas,Puerto Rico,Caribbean,PRI,"47,000,000"
172,172,Asia,Qatar,Western Asia,QAT,"3,500,000"
173,173,Africa,Réunion,Eastern Africa,REU,"859,000"
174,174,Europe,Romania,Eastern Europe,ROU,"24,000,000"
175,175,Europe,Russian Federation,Eastern Europe,RUS,"19,000,000"
176,176,Africa,Rwanda,Eastern Africa,RWA,"17,500,000"
177,177,Americas,Saint Barthélemy,Caribbean,BLM,"9,900"
178,178,Africa,"Saint Helena, Ascension and Tristan da Cunha",Western Africa,SHN,"6,000"
179,179,Americas,Saint Kitts and Nevis,Caribbean,KNA,"53,000"
180,180,Americas,Saint Lucia,Caribbean,LCA,"23,800,000"
181,181,Americas,Saint Martin (French part),Caribbean,MAF,"7,300,000"
182,182,Americas,Saint Pierre and Miquelon,Northern America,SPM,"5,700"
183,183,Americas,Saint Vincent and the Grenadines,Caribbean,VCT,"16,400,000"
184,184,Oceania,Samoa,Polynesia,WSM,"26,000,000"
185,185,Europe,San Marino,Southern Europe,SMR,"6,600,000"
186,186,Africa,Sao Tome and Principe,Middle Africa,STP,"33,000,000"
187,187,Asia,Saudi Arabia,Western Asia,SAU,"6,600,000"
188,188,Africa,Senegal,Western Africa,SEN,"2,300,000"
189,189,Europe,Serbia,Southern Europe,SRB,"6,900,000"
190,190,Africa,Seychelles,Eastern Africa,SYC,"98,000"
191,191,Africa,Sierra Leone,Western Africa,SLE,"7,900,000"
192,192,Asia,Singapore,South-Eastern Asia,SGP,"5,900,000"
193,193,Americas,Sint Maarten (Dutch part),Caribbean,SXM,"9,300,000"
194,194,Europe,Slovakia,Eastern Europe,SVK,"5,500,000"
195,195,Europe,Slovenia,Southern Europe,SVN,"276,000,000"
196,196,Oceania,Solomon Islands,Melanesia,SLB,"686,000"
197,197,Africa,Somalia,Eastern Africa,SOM,"19,100,000"
198,198,Africa,South Africa,Southern Africa,ZAF,"59,000,000"
199,199,Africa,South Sudan,Eastern Africa,SSD,"11,900,000"
200,200,Europe,Spain,Southern Europe,ESP,"47,000,000"
201,201,Asia,Sri Lanka,Southern Asia,LKA,"33,000,000"
202,202,Africa,Sudan,Northern Africa,SDN,"9,600,000"
203,203,Americas,Suriname,South America,SUR,"591,000"
204,204,Europe,Svalbard and Jan Mayen,Northern Europe,SJM,"4,000,000"
205,205,Africa,Swaziland,Southern Africa,SWZ,"1,200,000"
206,206,Europe,Sweden,Northern Europe,SWE,"10,700,000"
207,207,Europe,Switzerland,Western Europe,CHE,"8,700,000"
208,208,Asia,Syrian Arab Republic,Western Asia,SYR,"2,800,000"
209,209,Asia,"Taiwan, Province of China",Eastern Asia,TWN,"34,000,000"
210,210,Asia,Tajikistan,Central Asia,TJK,"9,500,000"
211,211,Africa,"Tanzania, United Republic of",Eastern Africa,TZA,"59,700,000"
212,212,Asia,Thailand,South-Eastern Asia,THA,"69,800,000"
213,213,Asia,Timor-Leste,South-Eastern Asia,TLS,"1,300,000"
214,214,Africa,Togo,Western Africa,TGO,"8,300,000"
215,215,Oceania,Tokelau,Polynesia,TKL,"2,000,000"
216,216,Oceania,Tonga,Polynesia,TON,"11,500,000"
217,217,Americas,Trinidad and Tobago,Caribbean,TTO,"1,900,000"
218,218,Africa,Tunisia,Northern Africa,TUN,"125,000,000"
219,219,Asia,Turkey,Western Asia,TUR,"84,000,000"
220,220,Asia,Turkmenistan,Central Asia,TKM,"6,000,000"
221,221,Americas,Turks and Caicos Islands,Caribbean,TCA,"69,800,000"
222,222,Oceania,Tuvalu,Polynesia,TUV,"15,000,000"
223,223,Africa,Uganda,Eastern Africa,UGA,"45,700,000"
224,224,Europe,Ukraine,Eastern Europe,UKR,"9,900,000"
225,225,Asia,United Arab Emirates,Western Asia,ARE,"9,900,000"
226,226,Europe,United Kingdom of Great Britain and Northern I...,Northern Europe,GBR,"68,000,000"
227,227,Americas,United States of America,Northern America,USA,"59,700,000"
228,228,Americas,Uruguay,South America,URY,"5,100,000"
229,229,Asia,Uzbekistan,Central Asia,UZB,"6,000,000"
230,230,Oceania,Vanuatu,Melanesia,VUT,"5,900,000"
231,231,Americas,Venezuela (Bolivarian Republic of),South America,VEN,"4,900,000"
232,232,Asia,Viet Nam,South-Eastern Asia,VNM,"97,000,000"
233,233,Americas,Virgin Islands (British),Caribbean,VGB,"5,800,000"
234,234,Americas,Virgin Islands (U.S.),Caribbean,VIR,"11,400,000"
235,235,Oceania,Wallis and Futuna,Polynesia,WLF,"15,900,000"
236,236,Africa,Western Sahara,Northern Africa,ESH,"597,000"
237,237,Asia,Yemen,Western Asia,YEM,"5,500,000"
238,238,Africa,Zambia,Eastern Africa,ZMB,"213,000,000"
239,239,Africa,Zimbabwe,Eastern Africa,ZWE,"19,100,000"

In [31]:
df.set_index(['continent']).sort_index()

,index,country,sub_region,code_3,Unnamed: 4
continent,,,,,
Africa,119,Libya,Northern Africa,LBY,"6,900,000"
Africa,134,Mauritius,Eastern Africa,MUS,"1,300,000"
Africa,133,Mauritania,Western Africa,MRT,"83,200,000"
Africa,129,Mali,Western Africa,MLI,"30,000,000"
Africa,126,Malawi,Eastern Africa,MWI,"25,800,000"
Africa,125,Madagascar,Eastern Africa,MDG,"4,300,000"
Africa,238,Zambia,Eastern Africa,ZMB,"213,000,000"
Africa,118,Liberia,Western Africa,LBR,"5,000,000"
Africa,117,Lesotho,Southern Africa,LSO,"27,700,000"
Africa,108,Kenya,Eastern Africa,KEN,"53,800,000"
Africa,87,Guinea-Bissau,Western Africa,GNB,"10,000,000"
Africa,86,Guinea,Western Africa,GIN,"18,700,000"
Africa,77,Ghana,Western Africa,GHA,"51,000,000"
Africa,74,Gambia,Western Africa,GMB,"3,000,000"
Africa,73,Gabon,Middle Africa,GAB,"28,000,000"
Africa,65,Ethiopia,Eastern Africa,ETH,"16,700,000"
Africa,63,Eritrea,Eastern Africa,ERI,"5,100,000"
Africa,62,Equatorial Guinea,Middle Africa,GNQ,"1,700,000"
Africa,60,Egypt,Northern Africa,EGY,"11,300,000"
Africa,56,Djibouti,Eastern Africa,DJI,"988,000"
Africa,135,Mayotte,Eastern Africa,MYT,"4,800,000"
Africa,49,Côte d'Ivoire,Western Africa,CIV,"38,000,000"
Africa,143,Morocco,Northern Africa,MAR,"6,800,000"
Africa,146,Namibia,Southern Africa,NAM,"3,200,000"
Africa,236,Western Sahara,Northern Africa,ESH,"597,000"
Africa,223,Uganda,Eastern Africa,UGA,"45,700,000"
Africa,218,Tunisia,Northern Africa,TUN,"125,000,000"
Africa,214,Togo,Western Africa,TGO,"8,300,000"
Africa,211,"Tanzania, United Republic of",Eastern Africa,TZA,"59,700,000"
Africa,205,Swaziland,Southern Africa,SWZ,"1,200,000"
Africa,202,Sudan,Northern Africa,SDN,"9,600,000"
Africa,199,South Sudan,Eastern Africa,SSD,"11,900,000"
Africa,198,South Africa,Southern Africa,ZAF,"59,000,000"
Africa,197,Somalia,Eastern Africa,SOM,"19,100,000"
Africa,191,Sierra Leone,Western Africa,SLE,"7,900,000"
Africa,190,Seychelles,Eastern Africa,SYC,"98,000"
Africa,188,Senegal,Western Africa,SEN,"2,300,000"
Africa,186,Sao Tome and Principe,Middle Africa,STP,"33,000,000"
Africa,178,"Saint Helena, Ascension and Tristan da Cunha",Western Africa,SHN,"6,000"
Africa,176,Rwanda,Eastern Africa,RWA,"17,500,000"
Africa,173,Réunion,Eastern Africa,REU,"859,000"
Africa,154,Nigeria,Western Africa,NGA,"31,000,000"
Africa,153,Niger,Western Africa,NER,"35,000,000"
Africa,144,Mozambique,Eastern Africa,MOZ,"51,600,000"
Africa,46,Congo (Democratic Republic of the),Middle Africa,COD,"89,000,000"
Africa,239,Zimbabwe,Eastern Africa,ZWE,"19,100,000"
Africa,44,Comoros,Eastern Africa,COM,"870,000"
Africa,32,Burkina Faso,Western Africa,BFA,"31,000,000"
Africa,36,Cameroon,Middle Africa,CMR,"38,000,000"
Africa,39,Central African Republic,Middle Africa,CAF,"84,000,000"
Africa,40,Chad,Middle Africa,TCD,"2,100,000"
Africa,22,Benin,Western Africa,BEN,"17,400,000"
Africa,6,Angola,Middle Africa,AGO,"54,000,000"
Africa,45,Congo,Middle Africa,COG,"5,500,000"
Africa,34,Cabo Verde,Western Africa,CPV,"556,000"
Africa,28,Botswana,Southern Africa,BWA,"29,000,000"
Africa,33,Burundi,Eastern Africa,BDI,"128,000,000"
Africa,3,Algeria,Northern Africa,DZA,"9,500,000"
Americas,29,Brazil,South America,BRA,"32,700,000"
Americas,165,Paraguay,South America,PRY,"7,100,000"
Americas,163,Panama,Central America,PAN,"8,700,000"
Americas,18,Barbados,Caribbean,BRB,"44,000,000"
Americas,25,Bolivia (Plurinational State of),South America,BOL,"12,900,000"
Americas,21,Belize,Central America,BLZ,"9,000,000"
Americas,26,"Bonaire, Sint Eustatius and Saba",Caribbean,BES,"4,300,000"
Americas,166,Peru,South America,PER,"59,000,000"
Americas,136,Mexico,Central America,MEX,"18,400,000"
Americas,23,Bermuda,Northern America,BMU,"64,000"
Americas,132,Martinique,Caribbean,MTQ,"6,900,000"
Americas,152,Nicaragua,Central America,NIC,"6,600,000"
Americas,171,Puerto Rico,Caribbean,PRI,"47,000,000"
Americas,179,Saint Kitts and Nevis,Caribbean,KNA,"53,000"
Americas,15,Bahamas,Caribbean,BHS,"7,500,000"
Americas,234,Virgin Islands (U.S.),Caribbean,VIR,"11,400,000"
Americas,233,Virgin Islands (British),Caribbean,VGB,"5,800,000"
Americas,231,Venezuela (Bolivarian Republic of),South America,VEN,"4,900,000"
Americas,228,Uruguay,South America,URY,"5,100,000"
Americas,227,United States of America,Northern America,USA,"59,700,000"
Americas,221,Turks and Caicos Islands,Caribbean,TCA,"69,800,000"
Americas,217,Trinidad and Tobago,Caribbean,TTO,"1,900,000"
Americas,203,Suriname,South America,SUR,"591,000"
Americas,7,Anguilla,Caribbean,AIA,"2,100,000"
Americas,8,Antigua and Barbuda,Caribbean,ATG,"98,000"
Americas,9,Argentina,South America,ARG,"45,000,000"
Americas,193,Sint Maarten (Dutch part),Caribbean,SXM,"9,300,000"
Americas,11,Aruba,Caribbean,ABW,"11,600,000"
Americas,183,Saint Vincent and the Grenadines,Caribbean,VCT,"16,400,000"
Americas,182,Saint Pierre and Miquelon,Northern America,SPM,"5,700"
Americas,181,Saint Martin (French part),Caribbean,MAF,"7,300,000"
Americas,180,Saint Lucia,Caribbean,LCA,"23,800,000"
Americas,177,Saint Barthélemy,Caribbean,BLM,"9,900"
Americas,103,Jamaica,Caribbean,JAM,"3,700,000"
Americas,142,Montserrat,Caribbean,MSR,"5,000"
Americas,66,Falkland Islands (Malvinas),South America,FLK,"5,500,000"
Americas,84,Guatemala,Central America,GTM,"21,000,000"
Americas,38,Cayman Islands,Caribbean,CYM,"66,000"
Americas,80,Greenland,Northern America,GRL,"56,000"
Americas,88,Guyana,South America,GUY,"787,000"
Americas,52,Curaçao,Caribbean,CUW,"2,600,000"
Americas,57,Dominica,Caribbean,DMA,"72,000"
Americas,89,Haiti,Caribbean,HTI,"114,000,000"
Americas,58,Dominican Republic,Caribbean,DOM,"11,200,000"
Americas,51,Cuba,Caribbean,CUB,"110,000,000"
Americas,59,Ecuador,South America,ECU,"2,900,000"
Americas,81,Grenada,Caribbean,GRD,"16,700,000"
Americas,41,Chile,South America,CHL,"25,000,000"
Americas,37,Canada,Northern America,CAN,"60,000,000"
Americas,82,Guadeloupe,Caribbean,GLP,"9,000,000"
Americas,43,Colombia,South America,COL,"51,000,000"
Americas,91,Honduras,Central America,HND,"10,000,000"
Americas,61,El Salvador,Central America,SLV,"6,500,000"
Americas,48,Costa Rica,Central America,CRI,"5,100,000"
Americas,71,French Guiana,South America,GUF,"45,000,000"
Asia,14,Azerbaijan,Western Asia,AZE,"10,000,000"
Asia,16,Bahrain,Western Asia,BHR,"1,900,000"
Asia,210,Tajikistan,Central Asia,TJK,"9,500,000"
Asia,140,Mongolia,Eastern Asia,MNG,"5,000,000"
Asia,209,"Taiwan, Province of China",Eastern Asia,TWN,"34,000,000"
Asia,187,Saudi Arabia,Western Asia,SAU,"6,600,000"
Asia,208,Syrian Arab Republic,Western Asia,SYR,"2,800,000"
Asia,17,Bangladesh,Southern Asia,BGD,"2,500,000"
Asia,172,Qatar,Western Asia,QAT,"3,500,000"
Asia,145,Myanmar,South-Eastern Asia,MMR,"54,000,000"
Asia,42,China,Eastern Asia,CHN,"1,412,000,000"
Asia,92,Hong Kong,Eastern Asia,HKG,"7,500,000"
Asia,35,Cambodia,South-Eastern Asia,KHM,"2,200,000"
Asia,201,Sri Lanka,Southern Asia,LKA,"33,000,000"
Asia,192,Singapore,South-Eastern Asia,SGP,"5,900,000"
Asia,167,Philippines,South-Eastern Asia,PHL,"13,100,000"
Asia,159,Oman,Western Asia,OMN,"5,000,000"
Asia,160,Pakistan,Southern Asia,PAK,"331,000,000"
Asia,162,"Palestine, State of",Western Asia,PSE,"5,100,000"
Asia,75,Georgia,Western Asia,GEO,"5,400,000"
Asia,148,Nepal,Southern Asia,NPL,"44,000,000"
Asia,10,Armenia,Western Asia,ARM,"45,700,000"
Asia,0,Afghanistan,Southern Asia,AFG,"6,900,000"
Asia,213,Timor-Leste,South-Eastern Asia,TLS,"1,300,000"
Asia,113,Kyrgyzstan,Central Asia,KGZ,"6,600,000"
Asia,24,Bhutan,Southern Asia,BTN,"771,000"
Asia,112,Kuwait,Western Asia,KWT,"8,300,000"
Asia,111,Korea (Republic of),Eastern Asia,KOR,"51,600,000"
Asia,110,Korea (Democratic People's Republic of),Eastern Asia,PRK,"38,000,000"
Asia,229,Uzbekistan,Central Asia,UZB,"6,000,000"
Asia,107,Kazakhstan,Central Asia,KAZ,"22,000,000"
Asia,114,Lao People's Democratic Republic,South-Eastern Asia,LAO,"7,300,000"
Asia,106,Jordan,Western Asia,JOR,"10,300,000"
Asia,232,Viet Nam,South-Eastern Asia,VNM,"97,000,000"
Asia,101,Israel,Western Asia,ISR,"9,300,000"
Asia,98,Iraq,Western Asia,IRQ,"89,000,000"
Asia,97,Iran (Islamic Republic of),Southern Asia,IRN,"84,000,000"
Asia,96,Indonesia,South-Eastern Asia,IDN,"4,600,000"
Asia,95,India,Southern Asia,IND,"1,400,000,000"
Asia,237,Yemen,Western Asia,YEM,"5,500,000"
Asia,104,Japan,Eastern Asia,JPN,"18,000,000"
Asia,116,Lebanon,Western Asia,LBN,"6,800,000"
Asia,212,Thailand,South-Eastern Asia,THA,"69,800,000"
Asia,220,Turkmenistan,Central Asia,TKM,"6,000,000"
Asia,30,Brunei Darussalam,South-Eastern Asia,BRN,"9,400,000"
Asia,225,United Arab Emirates,Western Asia,ARE,"9,900,000"
Asia,53,Cyprus,Western Asia,CYP,"1,200,000"
Asia,219,Turkey,Western Asia,TUR,"84,000,000"
Asia,123,Macao,Eastern Asia,MAC,"650,000"
Asia,128,Maldives,Southern Asia,MDV,"540,000"
Asia,127,Malaysia,South-Eastern Asia,MYS,"53,800,000"
Europe,64,Estonia,Northern Europe,EST,"1,300,000"
Europe,185,San Marino,Southern Europe,SMR,"6,600,000"
Europe,54,Czech Republic,Eastern Europe,CZE,"102,000,000"
Europe,5,Andorra,Southern Europe,AND,"77,000"
Europe,13,Austria,Western Europe,AUT,"9,000,000"
Europe,1,Åland Islands,Northern Europe,ALA,"5,500,000"
Europe,226,United Kingdom of Great Britain and Northern I...,Northern Europe,GBR,"68,000,000"
Europe,200,Spain,Southern Europe,ESP,"47,000,000"
Europe,207,Switzerland,Western Europe,CHE,"8,700,000"
Europe,206,Sweden,Northern Europe,SWE,"10,700,000"
Europe,55,Denmark,Northern Europe,DNK,"5,800,000"
Europe,50,Croatia,Southern Europe,HRV,"7,900,000"
Europe,2,Albania,Southern Europe,ALB,"3,300,000"
Europe,194,Slovakia,Eastern Europe,SVK,"5,500,000"
Europe,204,Svalbard and Jan Mayen,Northern Europe,SJM,"4,000,000"
Europe,224,Ukraine,Eastern Europe,UKR,"9,900,000"
Europe,189,Serbia,Southern Europe,SRB,"6,900,000"
Europe,195,Slovenia,Southern Europe,SVN,"276,000,000"
Europe,93,Hungary,Eastern Europe,HUN,"9,600,000"
Europe,138,Moldova (Republic of),Eastern Europe,MDA,"3,300,000"
Europe,115,Latvia,Northern Europe,LVA,"10,000,000"
Europe,149,Netherlands,Western Europe,NLD,"2,800,000"
Europe,31,Bulgaria,Eastern Europe,BGR,"6,900,000"
Europe,20,Belgium,Western Europe,BEL,"12,000,000"
Europe,78,Gibraltar,Southern Europe,GIB,"6,500,000"
Europe,79,Greece,Southern Europe,GRC,"10,800,000"
Europe,130,Malta,Southern Europe,MLT,"97,000,000"
Europe,141,Montenegro,Southern Europe,MNE,"622,000"
Europe,67,Faroe Islands,Northern Europe,FRO,"49,000"
Europe,120,Liechtenstein,Western Europe,LIE,"68,000,000"
Europe,121,Lithuania,Northern Europe,LTU,"3,500,000"
Europe,122,Luxembourg,Western Europe,LUX,"633,000"
Europe,124,Macedonia (the former Yugoslav Republic of),Southern Europe,MKD,"26,000,000"
Europe,27,Bosnia and Herzegovina,Southern Europe,BIH,"5,000,000"
Europe,139,Monaco,Western Europe,MCO,"7,100,000"
Europe,76,Germany,Western Europe,DEU,"83,200,000"
Europe,19,Belarus,Eastern Europe,BLR,"9,400,000"
Europe,99,Ireland,Northern Europe,IRL,"5,000,000"
Europe,94,Iceland,Northern Europe,ISL,"6,900,000"
Europe,69,Finland,Northern Europe,FIN,"5,500,000"
Europe,70,France,Western Europe,FRA,"67,000,000"
Europe,175,Russian Federation,Eastern Europe,RUS,"19,000,000"
Europe,174,Romania,Eastern Europe,ROU,"24,000,000"
Europe,170,Portugal,Southern Europe,PRT,"10,400,000"
Europe,90,Holy See,Southern Europe,VAT,800
Europe,85,Guernsey,Northern Europe,GGY,"63,000"
Europe,100,Isle of Man,Northern Europe,IMN,"85,000"
Europe,158,Norway,Northern Europe,NOR,"5,400,000"
Europe,102,Italy,Southern Europe,ITA,"60,000,000"
Europe,105,Jersey,Northern Europe,JEY,"11,800,000"
Europe,169,Poland,Eastern Europe,POL,"67,000,000"
Oceania,235,Wallis and Futuna,Polynesia,WLF,"15,900,000"
Oceania,47,Cook Islands,Polynesia,COK,"206,000,000"
Oceania,222,Tuvalu,Polynesia,TUV,"15,000,000"
Oceania,109,Kiribati,Micronesia,KIR,"17,600,000"
Oceania,230,Vanuatu,Melanesia,VUT,"5,900,000"
Oceania,68,Fiji,Melanesia,FJI,"896,000"
Oceania,216,Tonga,Polynesia,TON,"11,500,000"
Oceania,184,Samoa,Polynesia,WSM,"26,000,000"
Oceania,12,Australia,Australia and New Zealand,AUS,"36,000,000"
Oceania,168,Pitcairn,Polynesia,PCN,"50,000,000"
Oceania,164,Papua New Guinea,Melanesia,PNG,"9,000,000"
Oceania,161,Palau,Micronesia,PLW,"220,000,000"
Oceania,196,Solomon Islands,Melanesia,SLB,"686,000"
Oceania,157,Northern Mariana Islands,Micronesia,MNP,"58,000"
Oceania,131,Marshall Islands,Micronesia,MHL,"59,000"
Oceania,156,Norfolk Island,Australia and New Zealand,NFK,"20,300,000"
Oceania,151,New Zealand,Australia and New Zealand,NZL,"84,000,000"
Oceania,150,New Caledonia,Melanesia,NCL,"44,000,000"
Oceania,147,Nauru,Micronesia,NRU,"144,000,000"
Oceania,137,Micronesia (Federated States of),Micronesia,FSM,"164,000,000"
Oceania,83,Guam,Micronesia,GUM,"2,800,000"
Oceania,4,American Samoa,Polynesia,ASM,"55,000"
Oceania,215,Tokelau,Polynesia,TKL,"2,000,000"
Oceania,155,Niue,Polynesia,NIU,"2,400,000"
Oceania,72,French Polynesia,Polynesia,PYF,"40,000,000"

In [33]:
df.set_index(['continent','sub_region']).sort_index()

                                     index  \
continent sub_region
Africa    Eastern Africa                33
          Eastern Africa                44
          Eastern Africa                56
          Eastern Africa                63
          Eastern Africa                65
          Eastern Africa               108
          Eastern Africa               125
          Eastern Africa               126
          Eastern Africa               134
          Eastern Africa               135
          Eastern Africa               144
          Eastern Africa               173
          Eastern Africa               176
          Eastern Africa               190
          Eastern Africa               197
          Eastern Africa               199
          Eastern Africa               211
          Eastern Africa               223
          Eastern Africa               238
          Eastern Africa               239
          Middle Africa                  6
          Middle Africa                 36
          Middle Africa                 39
          Middle Africa                 40
          Middle Africa                 45
          Middle Africa                 46
          Middle Africa                 62
          Middle Africa                 73
          Middle Africa                186
          Northern Africa                3
          Northern Africa               60
          Northern Africa              119
          Northern Africa              143
          Northern Africa              202
          Northern Africa              218
          Northern Africa              236
          Southern Africa               28
          Southern Africa              117
          Southern Africa              146
          Southern Africa              198
          Southern Africa              205
          Western Africa                22
          Western Africa                32
          Western Africa                34
          Western Africa                49
          Western Africa                74
          Western Africa                77
          Western Africa                86
          Western Africa                87
          Western Africa               118
          Western Africa               129
          Western Africa               133
          Western Africa               153
          Western Africa               154
          Western Africa               178
          Western Africa               188
          Western Africa               191
          Western Africa               214
Americas  Caribbean                      7
          Caribbean                      8
          Caribbean                     11
          Caribbean                     15
          Caribbean                     18
          Caribbean                     26
          Caribbean                     38
          Caribbean                     51
          Caribbean                     52
          Caribbean                     57
          Caribbean                     58
          Caribbean                     81
          Caribbean                     82
          Caribbean                     89
          Caribbean                    103
          Caribbean                    132
          Caribbean                    142
          Caribbean                    171
          Caribbean                    177
          Caribbean                    179
          Caribbean                    180
          Caribbean                    181
          Caribbean                    183
          Caribbean                    193
          Caribbean                    217
          Caribbean                    221
          Caribbean                    233
          Caribbean                    234
          Central America               21
          Central America               48
          Central America               61
          Central America               84
          Central America               91
          Central America              136
          Central America              152
          Central America              163
          Northern America              23
          Northern America              37
          Northern America              80
          Northern America             182
          Northern America             227
          South America                  9
          South America                 25
          South America                 29
          South America                 41
          South America                 43
          South America                 59
          South America                 66
          South America                 71
          South America                 88
          South America                165
          South America                166
          South America                203
          South America                228
          South America                231
Asia      Central Asia                 107
          Central Asia                 113
          Central Asia                 210
          Central Asia                 220
          Central Asia                 229
          Eastern Asia                  42
          Eastern Asia                  92
          Eastern Asia                 104
          Eastern Asia                 110
          Eastern Asia                 111
          Eastern Asia                 123
          Eastern Asia                 140
          Eastern Asia                 209
          South-Eastern Asia            30
          South-Eastern Asia            35
          South-Eastern Asia            96
          South-Eastern Asia           114
          South-Eastern Asia           127
          South-Eastern Asia           145
          South-Eastern Asia           167
          South-Eastern Asia           192
          South-Eastern Asia           212
          South-Eastern Asia           213
          South-Eastern Asia           232
          Southern Asia                  0
          Southern Asia                 17
          Southern Asia                 24
          Southern Asia                 95
          Southern Asia                 97
          Southern Asia                128
          Southern Asia                148
          Southern Asia                160
          Southern Asia                201
          Western Asia                  10
          Western Asia                  14
          Western Asia                  16
          Western Asia                  53
          Western Asia                  75
          Western Asia                  98
          Western Asia                 101
          Western Asia                 106
          Western Asia                 112
          Western Asia                 116
          Western Asia                 159
          Western Asia                 162
          Western Asia                 172
          Western Asia                 187
          Western Asia                 208
          Western Asia                 219
          Western Asia                 225
          Western Asia                 237
Europe    Eastern Europe                19
          Eastern Europe                31
          Eastern Europe                54
          Eastern Europe                93
          Eastern Europe               138
          Eastern Europe               169
          Eastern Europe               174
          Eastern Europe               175
          Eastern Europe               194
          Eastern Europe               224
          Northern Europe                1
          Northern Europe               55
          Northern Europe               64
          Northern Europe               67
          Northern Europe               69
          Northern Europe               85
          Northern Europe               94
          Northern Europe               99
          Northern Europe              100
          Northern Europe              105
          Northern Europe              115
          Northern Europe              121
          Northern Europe              158
          Northern Europe              204
          Northern Europe              206
          Northern Europe              226
          Southern Europe                2
          Southern Europe                5
          Southern Europe               27
          Southern Europe               50
          Southern Europe               78
          Southern Europe               79
          Southern Europe               90
          Southern Europe              102
          Southern Europe              124
          Southern Europe              130
          Southern Europe              141
          Southern Europe              170
          Southern Europe              185
          Southern Europe              189
          Southern Europe              195
          Southern Europe              200
          Western Europe                13
          Western Europe                20
          Western Europe                70
          Western Europe                76
          Western Europe               120
          Western Europe               122
          Western Europe               139
          Western Europe               149
          Western Europe               207
Oceania   Australia and New Zealand     12
          Australia and New Zealand    151
          Australia and New Zealand    156
          Melanesia                     68
          Melanesia                    150
          Melanesia                    164
          Melanesia                    196
          Melanesia                    230
          Micronesia                    83
          Micronesia                   109
          Micronesia                   131
          Micronesia                   137
          Micronesia                   147
          Micronesia                   157
          Micronesia                   161
          Polynesia                      4
          Polynesia                     47
          Polynesia                     72
          Polynesia                    155
          Polynesia                    168
          Polynesia                    184
          Polynesia                    215
          Polynesia                    216
          Polynesia                    222
          Polynesia                    235

                                                                               country  \
continent sub_region
Africa    Eastern Africa                                                       Burundi
          Eastern Africa                                                       Comoros
          Eastern Africa                                                      Djibouti
          Eastern Africa                                                       Eritrea
          Eastern Africa                                                      Ethiopia
          Eastern Africa                                                         Kenya
          Eastern Africa                                                    Madagascar
          Eastern Africa                                                        Malawi
          Eastern Africa                                                     Mauritius
          Eastern Africa                                                       Mayotte
          Eastern Africa                                                    Mozambique
          Eastern Africa                                                       Réunion
          Eastern Africa                                                        Rwanda
          Eastern Africa                                                    Seychelles
          Eastern Africa                                                       Somalia
          Eastern Africa                                                   South Sudan
          Eastern Africa                                  Tanzania, United Republic of
          Eastern Africa                                                        Uganda
          Eastern Africa                                                        Zambia
          Eastern Africa                                                      Zimbabwe
          Middle Africa                                                         Angola
          Middle Africa                                                       Cameroon
          Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
          Middle Africa                                              Equatorial Guinea
          Middle Africa                                                          Gabon
          Middle Africa                                          Sao Tome and Principe
          Northern Africa                                                      Algeria
          Northern Africa                                                        Egypt
          Northern Africa                                                        Libya
          Northern Africa                                                      Morocco
          Northern Africa                                                        Sudan
          Northern Africa                                                      Tunisia
          Northern Africa                                               Western Sahara
          Southern Africa                                                     Botswana
          Southern Africa                                                      Lesotho
          Southern Africa                                                      Namibia
          Southern Africa                                                 South Africa
          Southern Africa                                                    Swaziland
          Western Africa                                                         Benin
          Western Africa                                                  Burkina Faso
          Western Africa                                                    Cabo Verde
          Western Africa                                                 Côte d'Ivoire
          Western Africa                                                        Gambia
          Western Africa                                                         Ghana
          Western Africa                                                        Guinea
          Western Africa                                                 Guinea-Bissau
          Western Africa                                                       Liberia
          Western Africa                                                          Mali
          Western Africa                                                    Mauritania
          Western Africa                                                         Niger
          Western Africa                                                       Nigeria
          Western Africa                  Saint Helena, Ascension and Tristan da Cunha
          Western Africa                                                       Senegal
          Western Africa                                                  Sierra Leone
          Western Africa                                                          Togo
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          Caribbean                                                              Aruba
          Caribbean                                                            Bahamas
          Caribbean                                                           Barbados
          Caribbean                                   Bonaire, Sint Eustatius and Saba
          Caribbean                                                     Cayman Islands
          Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
          Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
          Caribbean                                                              Haiti
          Caribbean                                                            Jamaica
          Caribbean                                                         Martinique
          Caribbean                                                         Montserrat
          Caribbean                                                        Puerto Rico
          Caribbean                                                   Saint Barthélemy
          Caribbean                                              Saint Kitts and Nevis
          Caribbean                                                        Saint Lucia
          Caribbean                                         Saint Martin (French part)
          Caribbean                                   Saint Vincent and the Grenadines
          Caribbean                                          Sint Maarten (Dutch part)
          Caribbean                                                Trinidad and Tobago
          Caribbean                                           Turks and Caicos Islands
          Caribbean                                           Virgin Islands (British)
          Caribbean                                              Virgin Islands (U.S.)
          Central America                                                       Belize
          Central America                                                   Costa Rica
          Central America                                                  El Salvador
          Central America                                                    Guatemala
          Central America                                                     Honduras
          Central America                                                       Mexico
          Central America                                                    Nicaragua
          Central America                                                       Panama
          Northern America                                                     Bermuda
          Northern America                                                      Canada
          Northern America                                                   Greenland
          Northern America                                   Saint Pierre and Miquelon
          Northern America                                    United States of America
          South America                                                      Argentina
          South America                               Bolivia (Plurinational State of)
          South America                                                         Brazil
          South America                                                          Chile
          South America                                                       Colombia
          South America                                                        Ecuador
          South America                                    Falkland Islands (Malvinas)
          South America                                                  French Guiana
          South America                                                         Guyana
          South America                                                       Paraguay

In [34]:
df.set_index(['continent','sub_region']).sort_index(level = 'sub_region')

                                     index  \
continent sub_region
Oceania   Australia and New Zealand     12
          Australia and New Zealand    151
          Australia and New Zealand    156
Americas  Caribbean                      7
          Caribbean                      8
          Caribbean                     11
          Caribbean                     15
          Caribbean                     18
          Caribbean                     26
          Caribbean                     38
          Caribbean                     51
          Caribbean                     52
          Caribbean                     57
          Caribbean                     58
          Caribbean                     81
          Caribbean                     82
          Caribbean                     89
          Caribbean                    103
          Caribbean                    132
          Caribbean                    142
          Caribbean                    171
          Caribbean                    177
          Caribbean                    179
          Caribbean                    180
          Caribbean                    181
          Caribbean                    183
          Caribbean                    193
          Caribbean                    217
          Caribbean                    221
          Caribbean                    233
          Caribbean                    234
          Central America               21
          Central America               48
          Central America               61
          Central America               84
          Central America               91
          Central America              136
          Central America              152
          Central America              163
Asia      Central Asia                 107
          Central Asia                 113
          Central Asia                 210
          Central Asia                 220
          Central Asia                 229
Africa    Eastern Africa                33
          Eastern Africa                44
          Eastern Africa                56
          Eastern Africa                63
          Eastern Africa                65
          Eastern Africa               108
          Eastern Africa               125
          Eastern Africa               126
          Eastern Africa               134
          Eastern Africa               135
          Eastern Africa               144
          Eastern Africa               173
          Eastern Africa               176
          Eastern Africa               190
          Eastern Africa               197
          Eastern Africa               199
          Eastern Africa               211
          Eastern Africa               223
          Eastern Africa               238
          Eastern Africa               239
Asia      Eastern Asia                  42
          Eastern Asia                  92
          Eastern Asia                 104
          Eastern Asia                 110
          Eastern Asia                 111
          Eastern Asia                 123
          Eastern Asia                 140
          Eastern Asia                 209
Europe    Eastern Europe                19
          Eastern Europe                31
          Eastern Europe                54
          Eastern Europe                93
          Eastern Europe               138
          Eastern Europe               169
          Eastern Europe               174
          Eastern Europe               175
          Eastern Europe               194
          Eastern Europe               224
Oceania   Melanesia                     68
          Melanesia                    150
          Melanesia                    164
          Melanesia                    196
          Melanesia                    230
          Micronesia                    83
          Micronesia                   109
          Micronesia                   131
          Micronesia                   137
          Micronesia                   147
          Micronesia                   157
          Micronesia                   161
Africa    Middle Africa                  6
          Middle Africa                 36
          Middle Africa                 39
          Middle Africa                 40
          Middle Africa                 45
          Middle Africa                 46
          Middle Africa                 62
          Middle Africa                 73
          Middle Africa                186
          Northern Africa                3
          Northern Africa               60
          Northern Africa              119
          Northern Africa              143
          Northern Africa              202
          Northern Africa              218
          Northern Africa              236
Americas  Northern America              23
          Northern America              37
          Northern America              80
          Northern America             182
          Northern America             227
Europe    Northern Europe                1
          Northern Europe               55
          Northern Europe               64
          Northern Europe               67
          Northern Europe               69
          Northern Europe               85
          Northern Europe               94
          Northern Europe               99
          Northern Europe              100
          Northern Europe              105
          Northern Europe              115
          Northern Europe              121
          Northern Europe              158
          Northern Europe              204
          Northern Europe              206
          Northern Europe              226
Oceania   Polynesia                      4
          Polynesia                     47
          Polynesia                     72
          Polynesia                    155
          Polynesia                    168
          Polynesia                    184
          Polynesia                    215
          Polynesia                    216
          Polynesia                    222
          Polynesia                    235
Americas  South America                  9
          South America                 25
          South America                 29
          South America                 41
          South America                 43
          South America                 59
          South America                 66
          South America                 71
          South America                 88
          South America                165
          South America                166
          South America                203
          South America                228
          South America                231
Asia      South-Eastern Asia            30
          South-Eastern Asia            35
          South-Eastern Asia            96
          South-Eastern Asia           114
          South-Eastern Asia           127
          South-Eastern Asia           145
          South-Eastern Asia           167
          South-Eastern Asia           192
          South-Eastern Asia           212
          South-Eastern Asia           213
          South-Eastern Asia           232
Africa    Southern Africa               28
          Southern Africa              117
          Southern Africa              146
          Southern Africa              198
          Southern Africa              205
Asia      Southern Asia                  0
          Southern Asia                 17
          Southern Asia                 24
          Southern Asia                 95
          Southern Asia                 97
          Southern Asia                128
          Southern Asia                148
          Southern Asia                160
          Southern Asia                201
Europe    Southern Europe                2
          Southern Europe                5
          Southern Europe               27
          Southern Europe               50
          Southern Europe               78
          Southern Europe               79
          Southern Europe               90
          Southern Europe              102
          Southern Europe              124
          Southern Europe              130
          Southern Europe              141
          Southern Europe              170
          Southern Europe              185
          Southern Europe              189
          Southern Europe              195
          Southern Europe              200
Africa    Western Africa                22
          Western Africa                32
          Western Africa                34
          Western Africa                49
          Western Africa                74
          Western Africa                77
          Western Africa                86
          Western Africa                87
          Western Africa               118
          Western Africa               129
          Western Africa               133
          Western Africa               153
          Western Africa               154
          Western Africa               178
          Western Africa               188
          Western Africa               191
          Western Africa               214
Asia      Western Asia                  10
          Western Asia                  14
          Western Asia                  16
          Western Asia                  53
          Western Asia                  75
          Western Asia                  98
          Western Asia                 101
          Western Asia                 106
          Western Asia                 112
          Western Asia                 116
          Western Asia                 159
          Western Asia                 162
          Western Asia                 172
          Western Asia                 187
          Western Asia                 208
          Western Asia                 219
          Western Asia                 225
          Western Asia                 237
Europe    Western Europe                13
          Western Europe                20
          Western Europe                70
          Western Europe                76
          Western Europe               120
          Western Europe               122
          Western Europe               139
          Western Europe               149
          Western Europe               207

                                                                               country  \
continent sub_region
Oceania   Australia and New Zealand                                          Australia
          Australia and New Zealand                                        New Zealand
          Australia and New Zealand                                     Norfolk Island
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          Caribbean                                                              Aruba
          Caribbean                                                            Bahamas
          Caribbean                                                           Barbados
          Caribbean                                   Bonaire, Sint Eustatius and Saba
          Caribbean                                                     Cayman Islands
          Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
          Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
          Caribbean                                                              Haiti
          Caribbean                                                            Jamaica
          Caribbean                                                         Martinique
          Caribbean                                                         Montserrat
          Caribbean                                                        Puerto Rico
          Caribbean                                                   Saint Barthélemy
          Caribbean                                              Saint Kitts and Nevis
          Caribbean                                                        Saint Lucia
          Caribbean                                         Saint Martin (French part)
          Caribbean                                   Saint Vincent and the Grenadines
          Caribbean                                          Sint Maarten (Dutch part)
          Caribbean                                                Trinidad and Tobago
          Caribbean                                           Turks and Caicos Islands
          Caribbean                                           Virgin Islands (British)
          Caribbean                                              Virgin Islands (U.S.)
          Central America                                                       Belize
          Central America                                                   Costa Rica
          Central America                                                  El Salvador
          Central America                                                    Guatemala
          Central America                                                     Honduras
          Central America                                                       Mexico
          Central America                                                    Nicaragua
          Central America                                                       Panama
Asia      Central Asia                                                      Kazakhstan
          Central Asia                                                      Kyrgyzstan
          Central Asia                                                      Tajikistan
          Central Asia                                                    Turkmenistan
          Central Asia                                                      Uzbekistan
Africa    Eastern Africa                                                       Burundi
          Eastern Africa                                                       Comoros
          Eastern Africa                                                      Djibouti
          Eastern Africa                                                       Eritrea
          Eastern Africa                                                      Ethiopia
          Eastern Africa                                                         Kenya
          Eastern Africa                                                    Madagascar
          Eastern Africa                                                        Malawi
          Eastern Africa                                                     Mauritius
          Eastern Africa                                                       Mayotte
          Eastern Africa                                                    Mozambique
          Eastern Africa                                                       Réunion
          Eastern Africa                                                        Rwanda
          Eastern Africa                                                    Seychelles
          Eastern Africa                                                       Somalia
          Eastern Africa                                                   South Sudan
          Eastern Africa                                  Tanzania, United Republic of
          Eastern Africa                                                        Uganda
          Eastern Africa                                                        Zambia
          Eastern Africa                                                      Zimbabwe
Asia      Eastern Asia                                                           China
          Eastern Asia                                                       Hong Kong
          Eastern Asia                                                           Japan
          Eastern Asia                         Korea (Democratic People's Republic of)
          Eastern Asia                                             Korea (Republic of)
          Eastern Asia                                                           Macao
          Eastern Asia                                                        Mongolia
          Eastern Asia                                       Taiwan, Province of China
Europe    Eastern Europe                                                       Belarus
          Eastern Europe                                                      Bulgaria
          Eastern Europe                                                Czech Republic
          Eastern Europe                                                       Hungary
          Eastern Europe                                         Moldova (Republic of)
          Eastern Europe                                                        Poland
          Eastern Europe                                                       Romania
          Eastern Europe                                            Russian Federation
          Eastern Europe                                                      Slovakia
          Eastern Europe                                                       Ukraine
Oceania   Melanesia                                                               Fiji
          Melanesia                                                      New Caledonia
          Melanesia                                                   Papua New Guinea
          Melanesia                                                    Solomon Islands
          Melanesia                                                            Vanuatu
          Micronesia                                                              Guam
          Micronesia                                                          Kiribati
          Micronesia                                                  Marshall Islands
          Micronesia                                  Micronesia (Federated States of)
          Micronesia                                                             Nauru
          Micronesia                                          Northern Mariana Islands
          Micronesia                                                             Palau
Africa    Middle Africa                                                         Angola
          Middle Africa                                                       Cameroon
          Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
          Middle Africa                                              Equatorial Guinea
          Middle Africa                                                          Gabon
          Middle Africa                                          Sao Tome and Principe
          Northern Africa                                                      Algeria
          Northern Africa                                                        Egypt
          Northern Africa                                                        Libya
          Northern Africa                                                      Morocco
          Northern Africa                                                        Sudan
          Northern Africa                                                      Tunisia

In [36]:
df.set_index(['continent','sub_region'], inplace = True)

In [37]:
df

                                     index  \
continent sub_region
Asia      Southern Asia                  0
Europe    Northern Europe                1
          Southern Europe                2
Africa    Northern Africa                3
Oceania   Polynesia                      4
Europe    Southern Europe                5
Africa    Middle Africa                  6
Americas  Caribbean                      7
          Caribbean                      8
          South America                  9
Asia      Western Asia                  10
Americas  Caribbean                     11
Oceania   Australia and New Zealand     12
Europe    Western Europe                13
Asia      Western Asia                  14
Americas  Caribbean                     15
Asia      Western Asia                  16
          Southern Asia                 17
Americas  Caribbean                     18
Europe    Eastern Europe                19
          Western Europe                20
Americas  Central America               21
Africa    Western Africa                22
Americas  Northern America              23
Asia      Southern Asia                 24
Americas  South America                 25
          Caribbean                     26
Europe    Southern Europe               27
Africa    Southern Africa               28
Americas  South America                 29
Asia      South-Eastern Asia            30
Europe    Eastern Europe                31
Africa    Western Africa                32
          Eastern Africa                33
          Western Africa                34
Asia      South-Eastern Asia            35
Africa    Middle Africa                 36
Americas  Northern America              37
          Caribbean                     38
Africa    Middle Africa                 39
          Middle Africa                 40
Americas  South America                 41
Asia      Eastern Asia                  42
Americas  South America                 43
Africa    Eastern Africa                44
          Middle Africa                 45
          Middle Africa                 46
Oceania   Polynesia                     47
Americas  Central America               48
Africa    Western Africa                49
Europe    Southern Europe               50
Americas  Caribbean                     51
          Caribbean                     52
Asia      Western Asia                  53
Europe    Eastern Europe                54
          Northern Europe               55
Africa    Eastern Africa                56
Americas  Caribbean                     57
          Caribbean                     58
          South America                 59
Africa    Northern Africa               60
Americas  Central America               61
Africa    Middle Africa                 62
          Eastern Africa                63
Europe    Northern Europe               64
Africa    Eastern Africa                65
Americas  South America                 66
Europe    Northern Europe               67
Oceania   Melanesia                     68
Europe    Northern Europe               69
          Western Europe                70
Americas  South America                 71
Oceania   Polynesia                     72
Africa    Middle Africa                 73
          Western Africa                74
Asia      Western Asia                  75
Europe    Western Europe                76
Africa    Western Africa                77
Europe    Southern Europe               78
          Southern Europe               79
Americas  Northern America              80
          Caribbean                     81
          Caribbean                     82
Oceania   Micronesia                    83
Americas  Central America               84
Europe    Northern Europe               85
Africa    Western Africa                86
          Western Africa                87
Americas  South America                 88
          Caribbean                     89
Europe    Southern Europe               90
Americas  Central America               91
Asia      Eastern Asia                  92
Europe    Eastern Europe                93
          Northern Europe               94
Asia      Southern Asia                 95
          South-Eastern Asia            96
          Southern Asia                 97
          Western Asia                  98
Europe    Northern Europe               99
          Northern Europe              100
Asia      Western Asia                 101
Europe    Southern Europe              102
Americas  Caribbean                    103
Asia      Eastern Asia                 104
Europe    Northern Europe              105
Asia      Western Asia                 106
          Central Asia                 107
Africa    Eastern Africa               108
Oceania   Micronesia                   109
Asia      Eastern Asia                 110
          Eastern Asia                 111
          Western Asia                 112
          Central Asia                 113
          South-Eastern Asia           114
Europe    Northern Europe              115
Asia      Western Asia                 116
Africa    Southern Africa              117
          Western Africa               118
          Northern Africa              119
Europe    Western Europe               120
          Northern Europe              121
          Western Europe               122
Asia      Eastern Asia                 123
Europe    Southern Europe              124
Africa    Eastern Africa               125
          Eastern Africa               126
Asia      South-Eastern Asia           127
          Southern Asia                128
Africa    Western Africa               129
Europe    Southern Europe              130
Oceania   Micronesia                   131
Americas  Caribbean                    132
Africa    Western Africa               133
          Eastern Africa               134
          Eastern Africa               135
Americas  Central America              136
Oceania   Micronesia                   137
Europe    Eastern Europe               138
          Western Europe               139
Asia      Eastern Asia                 140
Europe    Southern Europe              141
Americas  Caribbean                    142
Africa    Northern Africa              143
          Eastern Africa               144
Asia      South-Eastern Asia           145
Africa    Southern Africa              146
Oceania   Micronesia                   147
Asia      Southern Asia                148
Europe    Western Europe               149
Oceania   Melanesia                    150
          Australia and New Zealand    151
Americas  Central America              152
Africa    Western Africa               153
          Western Africa               154
Oceania   Polynesia                    155
          Australia and New Zealand    156
          Micronesia                   157
Europe    Northern Europe              158
Asia      Western Asia                 159
          Southern Asia                160
Oceania   Micronesia                   161
Asia      Western Asia                 162
Americas  Central America              163
Oceania   Melanesia                    164
Americas  South America                165
          South America                166
Asia      South-Eastern Asia           167
Oceania   Polynesia                    168
Europe    Eastern Europe               169
          Southern Europe              170
Americas  Caribbean                    171
Asia      Western Asia                 172
Africa    Eastern Africa               173
Europe    Eastern Europe               174
          Eastern Europe               175
Africa    Eastern Africa               176
Americas  Caribbean                    177
Africa    Western Africa               178
Americas  Caribbean                    179
          Caribbean                    180
          Caribbean                    181
          Northern America             182
          Caribbean                    183
Oceania   Polynesia                    184
Europe    Southern Europe              185
Africa    Middle Africa                186
Asia      Western Asia                 187
Africa    Western Africa               188
Europe    Southern Europe              189
Africa    Eastern Africa               190
          Western Africa               191
Asia      South-Eastern Asia           192
Americas  Caribbean                    193
Europe    Eastern Europe               194
          Southern Europe              195
Oceania   Melanesia                    196
Africa    Eastern Africa               197
          Southern Africa              198
          Eastern Africa               199
Europe    Southern Europe              200
Asia      Southern Asia                201
Africa    Northern Africa              202
Americas  South America                203
Europe    Northern Europe              204
Africa    Southern Africa              205
Europe    Northern Europe              206
          Western Europe               207
Asia      Western Asia                 208
          Eastern Asia                 209
          Central Asia                 210
Africa    Eastern Africa               211
Asia      South-Eastern Asia           212
          South-Eastern Asia           213
Africa    Western Africa               214
Oceania   Polynesia                    215
          Polynesia                    216
Americas  Caribbean                    217
Africa    Northern Africa              218
Asia      Western Asia                 219
          Central Asia                 220
Americas  Caribbean                    221
Oceania   Polynesia                    222
Africa    Eastern Africa               223
Europe    Eastern Europe               224
Asia      Western Asia                 225
Europe    Northern Europe              226
Americas  Northern America             227
          South America                228
Asia      Central Asia                 229
Oceania   Melanesia                    230
Americas  South America                231
Asia      South-Eastern Asia           232
Americas  Caribbean                    233
          Caribbean                    234
Oceania   Polynesia                    235
Africa    Northern Africa              236
Asia      Western Asia                 237
Africa    Eastern Africa               238
          Eastern Africa               239

                                                                               country  \
continent sub_region
Asia      Southern Asia                                                    Afghanistan
Europe    Northern Europe                                                Åland Islands
          Southern Europe                                                      Albania
Africa    Northern Africa                                                      Algeria
Oceania   Polynesia                                                     American Samoa
Europe    Southern Europe                                                      Andorra
Africa    Middle Africa                                                         Angola
Americas  Caribbean                                                           Anguilla
          Caribbean                                                Antigua and Barbuda
          South America                                                      Argentina
Asia      Western Asia                                                         Armenia
Americas  Caribbean                                                              Aruba
Oceania   Australia and New Zealand                                          Australia
Europe    Western Europe                                                       Austria
Asia      Western Asia                                                      Azerbaijan
Americas  Caribbean                                                            Bahamas
Asia      Western Asia                                                         Bahrain
          Southern Asia                                                     Bangladesh
Americas  Caribbean                                                           Barbados
Europe    Eastern Europe                                                       Belarus
          Western Europe                                                       Belgium
Americas  Central America                                                       Belize
Africa    Western Africa                                                         Benin
Americas  Northern America                                                     Bermuda
Asia      Southern Asia                                                         Bhutan
Americas  South America                               Bolivia (Plurinational State of)
          Caribbean                                   Bonaire, Sint Eustatius and Saba
Europe    Southern Europe                                       Bosnia and Herzegovina
Africa    Southern Africa                                                     Botswana
Americas  South America                                                         Brazil
Asia      South-Eastern Asia                                         Brunei Darussalam
Europe    Eastern Europe                                                      Bulgaria
Africa    Western Africa                                                  Burkina Faso
          Eastern Africa                                                       Burundi
          Western Africa                                                    Cabo Verde
Asia      South-Eastern Asia                                                  Cambodia
Africa    Middle Africa                                                       Cameroon
Americas  Northern America                                                      Canada
          Caribbean                                                     Cayman Islands
Africa    Middle Africa                                       Central African Republic
          Middle Africa                                                           Chad
Americas  South America                                                          Chile
Asia      Eastern Asia                                                           China
Americas  South America                                                       Colombia
Africa    Eastern Africa                                                       Comoros
          Middle Africa                                                          Congo
          Middle Africa                             Congo (Democratic Republic of the)
Oceania   Polynesia                                                       Cook Islands
Americas  Central America                                                   Costa Rica
Africa    Western Africa                                                 Côte d'Ivoire
Europe    Southern Europe                                                      Croatia
Americas  Caribbean                                                               Cuba
          Caribbean                                                            Curaçao
Asia      Western Asia                                                          Cyprus
Europe    Eastern Europe                                                Czech Republic
          Northern Europe                                                      Denmark
Africa    Eastern Africa                                                      Djibouti
Americas  Caribbean                                                           Dominica
          Caribbean                                                 Dominican Republic
          South America                                                        Ecuador
Africa    Northern Africa                                                        Egypt
Americas  Central America                                                  El Salvador
Africa    Middle Africa                                              Equatorial Guinea
          Eastern Africa                                                       Eritrea
Europe    Northern Europe                                                      Estonia
Africa    Eastern Africa                                                      Ethiopia
Americas  South America                                    Falkland Islands (Malvinas)
Europe    Northern Europe                                                Faroe Islands
Oceania   Melanesia                                                               Fiji
Europe    Northern Europe                                                      Finland
          Western Europe                                                        France
Americas  South America                                                  French Guiana
Oceania   Polynesia                                                   French Polynesia
Africa    Middle Africa                                                          Gabon
          Western Africa                                                        Gambia
Asia      Western Asia                                                         Georgia
Europe    Western Europe                                                       Germany
Africa    Western Africa                                                         Ghana
Europe    Southern Europe                                                    Gibraltar
          Southern Europe                                                       Greece
Americas  Northern America                                                   Greenland
          Caribbean                                                            Grenada
          Caribbean                                                         Guadeloupe
Oceania   Micronesia                                                              Guam
Americas  Central America                                                    Guatemala
Europe    Northern Europe                                                     Guernsey
Africa    Western Africa                                                        Guinea
          Western Africa                                                 Guinea-Bissau
Americas  South America                                                         Guyana
          Caribbean                                                              Haiti
Europe    Southern Europe                                                     Holy See
Americas  Central America                                                     Honduras
Asia      Eastern Asia                                                       Hong Kong
Europe    Eastern Europe                                                       Hungary
          Northern Europe                                                      Iceland
Asia      Southern Asia                                                          India
          South-Eastern Asia                                                 Indonesia
          Southern Asia                                     Iran (Islamic Republic of)
          Western Asia                                                            Iraq
Europe    Northern Europe                                                      Ireland
          Northern Europe                                                  Isle of Man
Asia      Western Asia                                                          Israel
Europe    Southern Europe                                                        Italy
Americas  Caribbean                                                            Jamaica
Asia      Eastern Asia                                                           Japan
Europe    Northern Europe                                                       Jersey
Asia      Western Asia                                                          Jordan
          Central Asia                                                      Kazakhstan
Africa    Eastern Africa                                                         Kenya

In [38]:
df.swaplevel('continent','sub_region')

                                     index  \
sub_region                continent
Southern Asia             Asia           0
Northern Europe           Europe         1
Southern Europe           Europe         2
Northern Africa           Africa         3
Polynesia                 Oceania        4
Southern Europe           Europe         5
Middle Africa             Africa         6
Caribbean                 Americas       7
                          Americas       8
South America             Americas       9
Western Asia              Asia          10
Caribbean                 Americas      11
Australia and New Zealand Oceania       12
Western Europe            Europe        13
Western Asia              Asia          14
Caribbean                 Americas      15
Western Asia              Asia          16
Southern Asia             Asia          17
Caribbean                 Americas      18
Eastern Europe            Europe        19
Western Europe            Europe        20
Central America           Americas      21
Western Africa            Africa        22
Northern America          Americas      23
Southern Asia             Asia          24
South America             Americas      25
Caribbean                 Americas      26
Southern Europe           Europe        27
Southern Africa           Africa        28
South America             Americas      29
South-Eastern Asia        Asia          30
Eastern Europe            Europe        31
Western Africa            Africa        32
Eastern Africa            Africa        33
Western Africa            Africa        34
South-Eastern Asia        Asia          35
Middle Africa             Africa        36
Northern America          Americas      37
Caribbean                 Americas      38
Middle Africa             Africa        39
                          Africa        40
South America             Americas      41
Eastern Asia              Asia          42
South America             Americas      43
Eastern Africa            Africa        44
Middle Africa             Africa        45
                          Africa        46
Polynesia                 Oceania       47
Central America           Americas      48
Western Africa            Africa        49
Southern Europe           Europe        50
Caribbean                 Americas      51
                          Americas      52
Western Asia              Asia          53
Eastern Europe            Europe        54
Northern Europe           Europe        55
Eastern Africa            Africa        56
Caribbean                 Americas      57
                          Americas      58
South America             Americas      59
Northern Africa           Africa        60
Central America           Americas      61
Middle Africa             Africa        62
Eastern Africa            Africa        63
Northern Europe           Europe        64
Eastern Africa            Africa        65
South America             Americas      66
Northern Europe           Europe        67
Melanesia                 Oceania       68
Northern Europe           Europe        69
Western Europe            Europe        70
South America             Americas      71
Polynesia                 Oceania       72
Middle Africa             Africa        73
Western Africa            Africa        74
Western Asia              Asia          75
Western Europe            Europe        76
Western Africa            Africa        77
Southern Europe           Europe        78
                          Europe        79
Northern America          Americas      80
Caribbean                 Americas      81
                          Americas      82
Micronesia                Oceania       83
Central America           Americas      84
Northern Europe           Europe        85
Western Africa            Africa        86
                          Africa        87
South America             Americas      88
Caribbean                 Americas      89
Southern Europe           Europe        90
Central America           Americas      91
Eastern Asia              Asia          92
Eastern Europe            Europe        93
Northern Europe           Europe        94
Southern Asia             Asia          95
South-Eastern Asia        Asia          96
Southern Asia             Asia          97
Western Asia              Asia          98
Northern Europe           Europe        99
                          Europe       100
Western Asia              Asia         101
Southern Europe           Europe       102
Caribbean                 Americas     103
Eastern Asia              Asia         104
Northern Europe           Europe       105
Western Asia              Asia         106
Central Asia              Asia         107
Eastern Africa            Africa       108
Micronesia                Oceania      109
Eastern Asia              Asia         110
                          Asia         111
Western Asia              Asia         112
Central Asia              Asia         113
South-Eastern Asia        Asia         114
Northern Europe           Europe       115
Western Asia              Asia         116
Southern Africa           Africa       117
Western Africa            Africa       118
Northern Africa           Africa       119
Western Europe            Europe       120
Northern Europe           Europe       121
Western Europe            Europe       122
Eastern Asia              Asia         123
Southern Europe           Europe       124
Eastern Africa            Africa       125
                          Africa       126
South-Eastern Asia        Asia         127
Southern Asia             Asia         128
Western Africa            Africa       129
Southern Europe           Europe       130
Micronesia                Oceania      131
Caribbean                 Americas     132
Western Africa            Africa       133
Eastern Africa            Africa       134
                          Africa       135
Central America           Americas     136
Micronesia                Oceania      137
Eastern Europe            Europe       138
Western Europe            Europe       139
Eastern Asia              Asia         140
Southern Europe           Europe       141
Caribbean                 Americas     142
Northern Africa           Africa       143
Eastern Africa            Africa       144
South-Eastern Asia        Asia         145
Southern Africa           Africa       146
Micronesia                Oceania      147
Southern Asia             Asia         148
Western Europe            Europe       149
Melanesia                 Oceania      150
Australia and New Zealand Oceania      151
Central America           Americas     152
Western Africa            Africa       153
                          Africa       154
Polynesia                 Oceania      155
Australia and New Zealand Oceania      156
Micronesia                Oceania      157
Northern Europe           Europe       158
Western Asia              Asia         159
Southern Asia             Asia         160
Micronesia                Oceania      161
Western Asia              Asia         162
Central America           Americas     163
Melanesia                 Oceania      164
South America             Americas     165
                          Americas     166
South-Eastern Asia        Asia         167
Polynesia                 Oceania      168
Eastern Europe            Europe       169
Southern Europe           Europe       170
Caribbean                 Americas     171
Western Asia              Asia         172
Eastern Africa            Africa       173
Eastern Europe            Europe       174
                          Europe       175
Eastern Africa            Africa       176
Caribbean                 Americas     177
Western Africa            Africa       178
Caribbean                 Americas     179
                          Americas     180
                          Americas     181
Northern America          Americas     182
Caribbean                 Americas     183
Polynesia                 Oceania      184
Southern Europe           Europe       185
Middle Africa             Africa       186
Western Asia              Asia         187
Western Africa            Africa       188
Southern Europe           Europe       189
Eastern Africa            Africa       190
Western Africa            Africa       191
South-Eastern Asia        Asia         192
Caribbean                 Americas     193
Eastern Europe            Europe       194
Southern Europe           Europe       195
Melanesia                 Oceania      196
Eastern Africa            Africa       197
Southern Africa           Africa       198
Eastern Africa            Africa       199
Southern Europe           Europe       200
Southern Asia             Asia         201
Northern Africa           Africa       202
South America             Americas     203
Northern Europe           Europe       204
Southern Africa           Africa       205
Northern Europe           Europe       206
Western Europe            Europe       207
Western Asia              Asia         208
Eastern Asia              Asia         209
Central Asia              Asia         210
Eastern Africa            Africa       211
South-Eastern Asia        Asia         212
                          Asia         213
Western Africa            Africa       214
Polynesia                 Oceania      215
                          Oceania      216
Caribbean                 Americas     217
Northern Africa           Africa       218
Western Asia              Asia         219
Central Asia              Asia         220
Caribbean                 Americas     221
Polynesia                 Oceania      222
Eastern Africa            Africa       223
Eastern Europe            Europe       224
Western Asia              Asia         225
Northern Europe           Europe       226
Northern America          Americas     227
South America             Americas     228
Central Asia              Asia         229
Melanesia                 Oceania      230
South America             Americas     231
South-Eastern Asia        Asia         232
Caribbean                 Americas     233
                          Americas     234
Polynesia                 Oceania      235
Northern Africa           Africa       236
Western Asia              Asia         237
Eastern Africa            Africa       238
                          Africa       239

                                                                               country  \
sub_region                continent
Southern Asia             Asia                                             Afghanistan
Northern Europe           Europe                                         Åland Islands
Southern Europe           Europe                                               Albania
Northern Africa           Africa                                               Algeria
Polynesia                 Oceania                                       American Samoa
Southern Europe           Europe                                               Andorra
Middle Africa             Africa                                                Angola
Caribbean                 Americas                                            Anguilla
                          Americas                                 Antigua and Barbuda
South America             Americas                                           Argentina
Western Asia              Asia                                                 Armenia
Caribbean                 Americas                                               Aruba
Australia and New Zealand Oceania                                            Australia
Western Europe            Europe                                               Austria
Western Asia              Asia                                              Azerbaijan
Caribbean                 Americas                                             Bahamas
Western Asia              Asia                                                 Bahrain
Southern Asia             Asia                                              Bangladesh
Caribbean                 Americas                                            Barbados
Eastern Europe            Europe                                               Belarus
Western Europe            Europe                                               Belgium
Central America           Americas                                              Belize
Western Africa            Africa                                                 Benin
Northern America          Americas                                             Bermuda
Southern Asia             Asia                                                  Bhutan
South America             Americas                    Bolivia (Plurinational State of)
Caribbean                 Americas                    Bonaire, Sint Eustatius and Saba
Southern Europe           Europe                                Bosnia and Herzegovina
Southern Africa           Africa                                              Botswana
South America             Americas                                              Brazil
South-Eastern Asia        Asia                                       Brunei Darussalam
Eastern Europe            Europe                                              Bulgaria
Western Africa            Africa                                          Burkina Faso
Eastern Africa            Africa                                               Burundi
Western Africa            Africa                                            Cabo Verde
South-Eastern Asia        Asia                                                Cambodia
Middle Africa             Africa                                              Cameroon
Northern America          Americas                                              Canada
Caribbean                 Americas                                      Cayman Islands
Middle Africa             Africa                              Central African Republic
                          Africa                                                  Chad
South America             Americas                                               Chile
Eastern Asia              Asia                                                   China
South America             Americas                                            Colombia
Eastern Africa            Africa                                               Comoros
Middle Africa             Africa                                                 Congo
                          Africa                    Congo (Democratic Republic of the)
Polynesia                 Oceania                                         Cook Islands
Central America           Americas                                          Costa Rica
Western Africa            Africa                                         Côte d'Ivoire
Southern Europe           Europe                                               Croatia
Caribbean                 Americas                                                Cuba
                          Americas                                             Curaçao
Western Asia              Asia                                                  Cyprus
Eastern Europe            Europe                                        Czech Republic
Northern Europe           Europe                                               Denmark
Eastern Africa            Africa                                              Djibouti
Caribbean                 Americas                                            Dominica
                          Americas                                  Dominican Republic
South America             Americas                                             Ecuador
Northern Africa           Africa                                                 Egypt
Central America           Americas                                         El Salvador
Middle Africa             Africa                                     Equatorial Guinea
Eastern Africa            Africa                                               Eritrea
Northern Europe           Europe                                               Estonia
Eastern Africa            Africa                                              Ethiopia
South America             Americas                         Falkland Islands (Malvinas)
Northern Europe           Europe                                         Faroe Islands
Melanesia                 Oceania                                                 Fiji
Northern Europe           Europe                                               Finland
Western Europe            Europe                                                France
South America             Americas                                       French Guiana
Polynesia                 Oceania                                     French Polynesia
Middle Africa             Africa                                                 Gabon
Western Africa            Africa                                                Gambia
Western Asia              Asia                                                 Georgia
Western Europe            Europe                                               Germany
Western Africa            Africa                                                 Ghana
Southern Europe           Europe                                             Gibraltar
                          Europe                                                Greece
Northern America          Americas                                           Greenland
Caribbean                 Americas                                             Grenada
                          Americas                                          Guadeloupe
Micronesia                Oceania                                                 Guam
Central America           Americas                                           Guatemala
Northern Europe           Europe                                              Guernsey
Western Africa            Africa                                                Guinea
                          Africa                                         Guinea-Bissau
South America             Americas                                              Guyana
Caribbean                 Americas                                               Haiti
Southern Europe           Europe                                              Holy See
Central America           Americas                                            Honduras
Eastern Asia              Asia                                               Hong Kong
Eastern Europe            Europe                                               Hungary
Northern Europe           Europe                                               Iceland
Southern Asia             Asia                                                   India
South-Eastern Asia        Asia                                               Indonesia
Southern Asia             Asia                              Iran (Islamic Republic of)
Western Asia              Asia                                                    Iraq
Northern Europe           Europe                                               Ireland
                          Europe                                           Isle of Man
Western Asia              Asia                                                  Israel
Southern Europe           Europe                                                 Italy
Caribbean                 Americas                                             Jamaica
Eastern Asia              Asia                                                   Japan
Northern Europe           Europe                                                Jersey
Western Asia              Asia                                                  Jordan
Central Asia              Asia                                              Kazakhstan

In [42]:
#Reshaping and Pivoting Indexes: Stocking combines multiple columns into a single column and adds a new index level while unstocking splits a single column into multiple columns.

In [40]:
df = pd.read_csv(r'C:\Users\nazom\OneDrive\Documents\Python Scripts\Pandas Folder\WorldContinents.csv', encoding = 'ISO-8859-1')
pd.set_option('display.max.rows',1350)
pd.set_option('display.max.columns',15)

In [41]:
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"